// src/lib/wordBankTech.ts
// Teknoloji kategorisi - 100+ kelime

import { WordData } from './wordBank';

export const techWords: WordData[] = [
    { word: 'algorithm', turkishTranslation: 'algoritma', definitionTr: 'Adım adım işlem', exampleSentence: 'The algorithm finds the best route.', exampleSentenceTr: 'Algoritma en iyi rotayı bulur.', type: 'noun', level: 'B2' },
    { word: 'application', turkishTranslation: 'uygulama', definitionTr: 'Yazılım programı', exampleSentence: 'Download the mobile application.', exampleSentenceTr: 'Mobil uygulamayı indirin.', type: 'noun', level: 'A2' },
    { word: 'artificial', turkishTranslation: 'yapay', definitionTr: 'İnsan yapımı', exampleSentence: 'Artificial intelligence is growing.', exampleSentenceTr: 'Yapay zeka gelişiyor.', type: 'adjective', level: 'B1' },
    { word: 'automate', turkishTranslation: 'otomatikleştirmek', definitionTr: 'Otomatik yapmak', exampleSentence: 'We can automate this process.', exampleSentenceTr: 'Bu süreci otomatikleştirebiliriz.', type: 'verb', level: 'B2' },
    { word: 'backup', turkishTranslation: 'yedek', definitionTr: 'Kopya', exampleSentence: 'Always keep a backup of your files.', exampleSentenceTr: 'Dosyalarınızın yedeğini her zaman tutun.', type: 'noun', level: 'A2' },
    { word: 'bandwidth', turkishTranslation: 'bant genişliği', definitionTr: 'Veri kapasitesi', exampleSentence: 'We need more bandwidth.', exampleSentenceTr: 'Daha fazla bant genişliğine ihtiyacımız var.', type: 'noun', level: 'B2' },
    { word: 'binary', turkishTranslation: 'ikili', definitionTr: 'İki değerli sistem', exampleSentence: 'Computers use binary code.', exampleSentenceTr: 'Bilgisayarlar ikili kod kullanır.', type: 'adjective', level: 'B2' },
    { word: 'blockchain', turkishTranslation: 'blok zinciri', definitionTr: 'Dağıtık defter', exampleSentence: 'Blockchain ensures security.', exampleSentenceTr: 'Blok zinciri güvenliği sağlar.', type: 'noun', level: 'B2' },
    { word: 'browser', turkishTranslation: 'tarayıcı', definitionTr: 'Web görüntüleyici', exampleSentence: 'Open your web browser.', exampleSentenceTr: 'Web tarayıcınızı açın.', type: 'noun', level: 'A2' },
    { word: 'bug', turkishTranslation: 'hata', definitionTr: 'Yazılım hatası', exampleSentence: 'There is a bug in the code.', exampleSentenceTr: 'Kodda bir hata var.', type: 'noun', level: 'B1' },
    { word: 'cache', turkishTranslation: 'önbellek', definitionTr: 'Geçici depo', exampleSentence: 'Clear the browser cache.', exampleSentenceTr: 'Tarayıcı önbelleğini temizleyin.', type: 'noun', level: 'B2' },
    { word: 'chip', turkishTranslation: 'çip', definitionTr: 'Entegre devre', exampleSentence: 'The chip is very small.', exampleSentenceTr: 'Çip çok küçük.', type: 'noun', level: 'B1' },
    { word: 'click', turkishTranslation: 'tıklamak', definitionTr: 'Fare ile seçmek', exampleSentence: 'Click the button to continue.', exampleSentenceTr: 'Devam etmek için butona tıklayın.', type: 'verb', level: 'A1' },
    { word: 'cloud', turkishTranslation: 'bulut', definitionTr: 'Uzak sunucu', exampleSentence: 'Store your data in the cloud.', exampleSentenceTr: 'Verilerinizi bulutta saklayın.', type: 'noun', level: 'A2' },
    { word: 'code', turkishTranslation: 'kod', definitionTr: 'Programlama dili', exampleSentence: 'I am learning to code.', exampleSentenceTr: 'Kod yazmayı öğreniyorum.', type: 'noun', level: 'A2' },
    { word: 'compatible', turkishTranslation: 'uyumlu', definitionTr: 'Birlikte çalışabilen', exampleSentence: 'Is this compatible with my device?', exampleSentenceTr: 'Bu cihazımla uyumlu mu?', type: 'adjective', level: 'B1' },
    { word: 'compile', turkishTranslation: 'derlemek', definitionTr: 'Kodu çevirmek', exampleSentence: 'Compile the source code.', exampleSentenceTr: 'Kaynak kodunu derleyin.', type: 'verb', level: 'B2' },
    { word: 'compress', turkishTranslation: 'sıkıştırmak', definitionTr: 'Küçültmek', exampleSentence: 'Compress the file before sending.', exampleSentenceTr: 'Göndermeden önce dosyayı sıkıştırın.', type: 'verb', level: 'B1' },
    { word: 'computer', turkishTranslation: 'bilgisayar', definitionTr: 'Elektronik cihaz', exampleSentence: 'Turn on the computer.', exampleSentenceTr: 'Bilgisayarı açın.', type: 'noun', level: 'A1' },
    { word: 'configure', turkishTranslation: 'yapılandırmak', definitionTr: 'Ayarlamak', exampleSentence: 'Configure the network settings.', exampleSentenceTr: 'Ağ ayarlarını yapılandırın.', type: 'verb', level: 'B2' },
    { word: 'connect', turkishTranslation: 'bağlanmak', definitionTr: 'Birleştirmek', exampleSentence: 'Connect to the Wi-Fi network.', exampleSentenceTr: 'Wi-Fi ağına bağlanın.', type: 'verb', level: 'A2' },
    { word: 'convert', turkishTranslation: 'dönüştürmek', definitionTr: 'Çevirmek', exampleSentence: 'Convert the file to PDF.', exampleSentenceTr: 'Dosyayı PDF\'e dönüştürün.', type: 'verb', level: 'B1' },
    { word: 'cookie', turkishTranslation: 'çerez', definitionTr: 'Tarayıcı verisi', exampleSentence: 'This site uses cookies.', exampleSentenceTr: 'Bu site çerez kullanıyor.', type: 'noun', level: 'B1' },
    { word: 'crash', turkishTranslation: 'çökmek', definitionTr: 'Durma', exampleSentence: 'The system crashed unexpectedly.', exampleSentenceTr: 'Sistem beklenmedik şekilde çöktü.', type: 'verb', level: 'B1' },
    { word: 'cursor', turkishTranslation: 'imleç', definitionTr: 'Ekran işareti', exampleSentence: 'Move the cursor to the right.', exampleSentenceTr: 'İmleci sağa hareket ettirin.', type: 'noun', level: 'A2' },
    { word: 'cybersecurity', turkishTranslation: 'siber güvenlik', definitionTr: 'Dijital koruma', exampleSentence: 'Cybersecurity is very important.', exampleSentenceTr: 'Siber güvenlik çok önemli.', type: 'noun', level: 'B2' },
    { word: 'data', turkishTranslation: 'veri', definitionTr: 'Bilgi', exampleSentence: 'Protect your personal data.', exampleSentenceTr: 'Kişisel verilerinizi koruyun.', type: 'noun', level: 'A2' },
    { word: 'database', turkishTranslation: 'veritabanı', definitionTr: 'Veri deposu', exampleSentence: 'The database stores all records.', exampleSentenceTr: 'Veritabanı tüm kayıtları saklar.', type: 'noun', level: 'B1' },
    { word: 'debug', turkishTranslation: 'hata ayıklamak', definitionTr: 'Hataları düzeltmek', exampleSentence: 'We need to debug the program.', exampleSentenceTr: 'Programın hatalarını ayıklamalıyız.', type: 'verb', level: 'B2' },
    { word: 'decrypt', turkishTranslation: 'şifre çözmek', definitionTr: 'Açık hale getirmek', exampleSentence: 'Decrypt the encrypted file.', exampleSentenceTr: 'Şifreli dosyanın şifresini çözün.', type: 'verb', level: 'B2' },
    { word: 'default', turkishTranslation: 'varsayılan', definitionTr: 'Otomatik ayar', exampleSentence: 'Use the default settings.', exampleSentenceTr: 'Varsayılan ayarları kullanın.', type: 'adjective', level: 'B1' },
    { word: 'delete', turkishTranslation: 'silmek', definitionTr: 'Kaldırmak', exampleSentence: 'Delete the old files.', exampleSentenceTr: 'Eski dosyaları silin.', type: 'verb', level: 'A2' },
    { word: 'deploy', turkishTranslation: 'dağıtmak', definitionTr: 'Yayına almak', exampleSentence: 'Deploy the application to the server.', exampleSentenceTr: 'Uygulamayı sunucuya dağıtın.', type: 'verb', level: 'B2' },
    { word: 'desktop', turkishTranslation: 'masaüstü', definitionTr: 'Bilgisayar ekranı', exampleSentence: 'Save the file to the desktop.', exampleSentenceTr: 'Dosyayı masaüstüne kaydedin.', type: 'noun', level: 'A2' },
    { word: 'developer', turkishTranslation: 'geliştirici', definitionTr: 'Yazılımcı', exampleSentence: 'She is a software developer.', exampleSentenceTr: 'O bir yazılım geliştiricisi.', type: 'noun', level: 'B1' },
    { word: 'device', turkishTranslation: 'cihaz', definitionTr: 'Alet', exampleSentence: 'Connect your device to the computer.', exampleSentenceTr: 'Cihazınızı bilgisayara bağlayın.', type: 'noun', level: 'A2' },
    { word: 'digital', turkishTranslation: 'dijital', definitionTr: 'Sayısal', exampleSentence: 'We live in a digital age.', exampleSentenceTr: 'Dijital çağda yaşıyoruz.', type: 'adjective', level: 'A2' },
    { word: 'domain', turkishTranslation: 'alan adı', definitionTr: 'Web adresi', exampleSentence: 'Register a domain name.', exampleSentenceTr: 'Bir alan adı kaydedin.', type: 'noun', level: 'B1' },
    { word: 'download', turkishTranslation: 'indirmek', definitionTr: 'Bilgisayara çekmek', exampleSentence: 'Download the latest version.', exampleSentenceTr: 'En son sürümü indirin.', type: 'verb', level: 'A2' },
    { word: 'drag', turkishTranslation: 'sürüklemek', definitionTr: 'Çekip bırakmak', exampleSentence: 'Drag the file to the folder.', exampleSentenceTr: 'Dosyayı klasöre sürükleyin.', type: 'verb', level: 'A2' },
    { word: 'drive', turkishTranslation: 'sürücü', definitionTr: 'Depolama birimi', exampleSentence: 'Save the file to the drive.', exampleSentenceTr: 'Dosyayı sürücüye kaydedin.', type: 'noun', level: 'A2' },
    { word: 'edit', turkishTranslation: 'düzenlemek', definitionTr: 'Değiştirmek', exampleSentence: 'Edit the document before sending.', exampleSentenceTr: 'Göndermeden önce belgeyi düzenleyin.', type: 'verb', level: 'A2' },
    { word: 'email', turkishTranslation: 'e-posta', definitionTr: 'Elektronik posta', exampleSentence: 'Send me an email.', exampleSentenceTr: 'Bana e-posta gönder.', type: 'noun', level: 'A1' },
    { word: 'embed', turkishTranslation: 'gömmek', definitionTr: 'İçine yerleştirmek', exampleSentence: 'Embed the video in the page.', exampleSentenceTr: 'Videoyu sayfaya gömün.', type: 'verb', level: 'B2' },
    { word: 'encrypt', turkishTranslation: 'şifrelemek', definitionTr: 'Korumak', exampleSentence: 'Encrypt your sensitive data.', exampleSentenceTr: 'Hassas verilerinizi şifreleyin.', type: 'verb', level: 'B2' },
    { word: 'error', turkishTranslation: 'hata', definitionTr: 'Yanlışlık', exampleSentence: 'An error occurred.', exampleSentenceTr: 'Bir hata oluştu.', type: 'noun', level: 'A2' },
    { word: 'ethernet', turkishTranslation: 'ethernet', definitionTr: 'Kablolu ağ', exampleSentence: 'Connect via ethernet cable.', exampleSentenceTr: 'Ethernet kablosuyla bağlanın.', type: 'noun', level: 'B2' },
    { word: 'execute', turkishTranslation: 'çalıştırmak', definitionTr: 'Yürütmek', exampleSentence: 'Execute the program.', exampleSentenceTr: 'Programı çalıştırın.', type: 'verb', level: 'B2' },
    { word: 'export', turkishTranslation: 'dışa aktarmak', definitionTr: 'Çıkarmak', exampleSentence: 'Export the data to CSV.', exampleSentenceTr: 'Verileri CSV\'ye aktarın.', type: 'verb', level: 'B1' },
    { word: 'file', turkishTranslation: 'dosya', definitionTr: 'Bilgi birimi', exampleSentence: 'Open the file to edit.', exampleSentenceTr: 'Düzenlemek için dosyayı açın.', type: 'noun', level: 'A1' },
    { word: 'filter', turkishTranslation: 'filtre', definitionTr: 'Süzgeç', exampleSentence: 'Apply a filter to the results.', exampleSentenceTr: 'Sonuçlara filtre uygulayın.', type: 'noun', level: 'B1' },
    { word: 'firewall', turkishTranslation: 'güvenlik duvarı', definitionTr: 'Koruma sistemi', exampleSentence: 'The firewall blocked the attack.', exampleSentenceTr: 'Güvenlik duvarı saldırıyı engelledi.', type: 'noun', level: 'B2' },
    { word: 'firmware', turkishTranslation: 'yazılım', definitionTr: 'Aygıt yazılımı', exampleSentence: 'Update the router firmware.', exampleSentenceTr: 'Yönlendirici yazılımını güncelleyin.', type: 'noun', level: 'B2' },
    { word: 'folder', turkishTranslation: 'klasör', definitionTr: 'Dosya kabı', exampleSentence: 'Create a new folder.', exampleSentenceTr: 'Yeni bir klasör oluşturun.', type: 'noun', level: 'A1' },
    { word: 'format', turkishTranslation: 'biçim', definitionTr: 'Düzen', exampleSentence: 'Choose the correct file format.', exampleSentenceTr: 'Doğru dosya biçimini seçin.', type: 'noun', level: 'A2' },
    { word: 'framework', turkishTranslation: 'çerçeve', definitionTr: 'Yazılım iskeleti', exampleSentence: 'We use the React framework.', exampleSentenceTr: 'React çerçevesini kullanıyoruz.', type: 'noun', level: 'B2' },
    { word: 'function', turkishTranslation: 'fonksiyon', definitionTr: 'İşlev', exampleSentence: 'This function returns a value.', exampleSentenceTr: 'Bu fonksiyon bir değer döndürür.', type: 'noun', level: 'B1' },
    { word: 'gadget', turkishTranslation: 'cihaz', definitionTr: 'Elektronik alet', exampleSentence: 'I love new gadgets.', exampleSentenceTr: 'Yeni cihazları seviyorum.', type: 'noun', level: 'B1' },
    { word: 'gigabyte', turkishTranslation: 'gigabayt', definitionTr: 'Veri birimi', exampleSentence: 'The file is 2 gigabytes.', exampleSentenceTr: 'Dosya 2 gigabayt.', type: 'noun', level: 'A2' },
    { word: 'graphics', turkishTranslation: 'grafikler', definitionTr: 'Görsel ögeler', exampleSentence: 'The game has amazing graphics.', exampleSentenceTr: 'Oyunun grafikleri harika.', type: 'noun', level: 'B1' },
    { word: 'hack', turkishTranslation: 'hacklemek', definitionTr: 'İzinsiz girmek', exampleSentence: 'Hackers tried to hack the system.', exampleSentenceTr: 'Hackerlar sistemi hacklemeye çalıştı.', type: 'verb', level: 'B1' },
    { word: 'hardware', turkishTranslation: 'donanım', definitionTr: 'Fiziksel parça', exampleSentence: 'Check the hardware components.', exampleSentenceTr: 'Donanım bileşenlerini kontrol edin.', type: 'noun', level: 'A2' },
    { word: 'homepage', turkishTranslation: 'ana sayfa', definitionTr: 'Başlangıç sayfası', exampleSentence: 'Visit our homepage.', exampleSentenceTr: 'Ana sayfamızı ziyaret edin.', type: 'noun', level: 'A2' },
    { word: 'host', turkishTranslation: 'barındırmak', definitionTr: 'Sunmak', exampleSentence: 'We host the website on this server.', exampleSentenceTr: 'Web sitesini bu sunucuda barındırıyoruz.', type: 'verb', level: 'B1' },
    { word: 'icon', turkishTranslation: 'simge', definitionTr: 'Küçük resim', exampleSentence: 'Click the icon to open.', exampleSentenceTr: 'Açmak için simgeye tıklayın.', type: 'noun', level: 'A2' },
    { word: 'import', turkishTranslation: 'içe aktarmak', definitionTr: 'Almak', exampleSentence: 'Import the data from Excel.', exampleSentenceTr: 'Verileri Excel\'den içe aktarın.', type: 'verb', level: 'B1' },
    { word: 'input', turkishTranslation: 'girdi', definitionTr: 'Giriş verisi', exampleSentence: 'Enter your input here.', exampleSentenceTr: 'Girdinizi buraya yazın.', type: 'noun', level: 'B1' },
    { word: 'install', turkishTranslation: 'yüklemek', definitionTr: 'Kurmak', exampleSentence: 'Install the software first.', exampleSentenceTr: 'Önce yazılımı yükleyin.', type: 'verb', level: 'A2' },
    { word: 'integrate', turkishTranslation: 'entegre etmek', definitionTr: 'Birleştirmek', exampleSentence: 'Integrate the two systems.', exampleSentenceTr: 'İki sistemi entegre edin.', type: 'verb', level: 'B2' },
    { word: 'interface', turkishTranslation: 'arayüz', definitionTr: 'Kullanıcı ekranı', exampleSentence: 'The interface is user-friendly.', exampleSentenceTr: 'Arayüz kullanıcı dostu.', type: 'noun', level: 'B1' },
    { word: 'internet', turkishTranslation: 'internet', definitionTr: 'Küresel ağ', exampleSentence: 'I need internet access.', exampleSentenceTr: 'İnternet erişimine ihtiyacım var.', type: 'noun', level: 'A1' },
    { word: 'keyboard', turkishTranslation: 'klavye', definitionTr: 'Yazı girişi', exampleSentence: 'My keyboard is broken.', exampleSentenceTr: 'Klavyem bozuk.', type: 'noun', level: 'A1' },
    { word: 'laptop', turkishTranslation: 'dizüstü', definitionTr: 'Taşınabilir bilgisayar', exampleSentence: 'Bring your laptop to the meeting.', exampleSentenceTr: 'Toplantıya dizüstünü getir.', type: 'noun', level: 'A1' },
    { word: 'launch', turkishTranslation: 'başlatmak', definitionTr: 'Piyasaya sürmek', exampleSentence: 'We will launch the app tomorrow.', exampleSentenceTr: 'Uygulamayı yarın başlatacağız.', type: 'verb', level: 'B1' },
    { word: 'link', turkishTranslation: 'bağlantı', definitionTr: 'URL', exampleSentence: 'Click on the link.', exampleSentenceTr: 'Bağlantıya tıklayın.', type: 'noun', level: 'A2' },
    { word: 'load', turkishTranslation: 'yüklemek', definitionTr: 'Açmak', exampleSentence: 'The page is still loading.', exampleSentenceTr: 'Sayfa hala yükleniyor.', type: 'verb', level: 'A2' },
    { word: 'log', turkishTranslation: 'kayıt', definitionTr: 'Günlük', exampleSentence: 'Check the system log.', exampleSentenceTr: 'Sistem kaydını kontrol edin.', type: 'noun', level: 'B1' },
    { word: 'login', turkishTranslation: 'giriş yapmak', definitionTr: 'Oturum açmak', exampleSentence: 'Login to your account.', exampleSentenceTr: 'Hesabınıza giriş yapın.', type: 'verb', level: 'A2' },
    { word: 'malware', turkishTranslation: 'zararlı yazılım', definitionTr: 'Kötü amaçlı program', exampleSentence: 'Scan for malware regularly.', exampleSentenceTr: 'Düzenli olarak zararlı yazılım tarayın.', type: 'noun', level: 'B2' },
    { word: 'memory', turkishTranslation: 'bellek', definitionTr: 'RAM', exampleSentence: 'The computer needs more memory.', exampleSentenceTr: 'Bilgisayar daha fazla belleğe ihtiyaç duyuyor.', type: 'noun', level: 'A2' },
    { word: 'menu', turkishTranslation: 'menü', definitionTr: 'Seçenek listesi', exampleSentence: 'Open the settings menu.', exampleSentenceTr: 'Ayarlar menüsünü açın.', type: 'noun', level: 'A1' },
    { word: 'mobile', turkishTranslation: 'mobil', definitionTr: 'Taşınabilir', exampleSentence: 'The mobile version works great.', exampleSentenceTr: 'Mobil sürüm harika çalışıyor.', type: 'adjective', level: 'A2' },
    { word: 'monitor', turkishTranslation: 'monitör', definitionTr: 'Ekran', exampleSentence: 'Buy a larger monitor.', exampleSentenceTr: 'Daha büyük bir monitör al.', type: 'noun', level: 'A2' },
    { word: 'mouse', turkishTranslation: 'fare', definitionTr: 'İşaretleme cihazı', exampleSentence: 'My mouse is not working.', exampleSentenceTr: 'Farem çalışmıyor.', type: 'noun', level: 'A1' },
    { word: 'navigate', turkishTranslation: 'gezinmek', definitionTr: 'Yol bulmak', exampleSentence: 'Navigate to the homepage.', exampleSentenceTr: 'Ana sayfaya gidin.', type: 'verb', level: 'B1' },
    { word: 'network', turkishTranslation: 'ağ', definitionTr: 'Bağlantı sistemi', exampleSentence: 'Connect to the network.', exampleSentenceTr: 'Ağa bağlanın.', type: 'noun', level: 'A2' },
    { word: 'notification', turkishTranslation: 'bildirim', definitionTr: 'Uyarı', exampleSentence: 'I received a notification.', exampleSentenceTr: 'Bir bildirim aldım.', type: 'noun', level: 'A2' },
    { word: 'offline', turkishTranslation: 'çevrimdışı', definitionTr: 'İnternetsiz', exampleSentence: 'The app works offline.', exampleSentenceTr: 'Uygulama çevrimdışı çalışıyor.', type: 'adjective', level: 'A2' },
    { word: 'online', turkishTranslation: 'çevrimiçi', definitionTr: 'İnternete bağlı', exampleSentence: 'Shop online for convenience.', exampleSentenceTr: 'Kolaylık için çevrimiçi alışveriş yapın.', type: 'adjective', level: 'A1' },
    { word: 'operate', turkishTranslation: 'çalıştırmak', definitionTr: 'İşletmek', exampleSentence: 'Learn how to operate the software.', exampleSentenceTr: 'Yazılımı nasıl çalıştıracağınızı öğrenin.', type: 'verb', level: 'B1' },
    { word: 'optimize', turkishTranslation: 'optimize etmek', definitionTr: 'En iyi duruma getirmek', exampleSentence: 'Optimize the code for speed.', exampleSentenceTr: 'Kodu hız için optimize edin.', type: 'verb', level: 'B2' },
    { word: 'output', turkishTranslation: 'çıktı', definitionTr: 'Sonuç verisi', exampleSentence: 'Check the output of the program.', exampleSentenceTr: 'Programın çıktısını kontrol edin.', type: 'noun', level: 'B1' },
    { word: 'password', turkishTranslation: 'şifre', definitionTr: 'Gizli kod', exampleSentence: 'Enter your password.', exampleSentenceTr: 'Şifrenizi girin.', type: 'noun', level: 'A1' },
    { word: 'paste', turkishTranslation: 'yapıştırmak', definitionTr: 'Kopyayı koymak', exampleSentence: 'Copy and paste the text.', exampleSentenceTr: 'Metni kopyalayıp yapıştırın.', type: 'verb', level: 'A2' },
    { word: 'platform', turkishTranslation: 'platform', definitionTr: 'İşletim ortamı', exampleSentence: 'The platform supports all devices.', exampleSentenceTr: 'Platform tüm cihazları destekliyor.', type: 'noun', level: 'B1' },
    { word: 'plugin', turkishTranslation: 'eklenti', definitionTr: 'Ek yazılım', exampleSentence: 'Install the plugin first.', exampleSentenceTr: 'Önce eklentiyi yükleyin.', type: 'noun', level: 'B1' },
    { word: 'port', turkishTranslation: 'port', definitionTr: 'Bağlantı noktası', exampleSentence: 'Connect the cable to the USB port.', exampleSentenceTr: 'Kabloyu USB portuna bağlayın.', type: 'noun', level: 'B1' },
    { word: 'process', turkishTranslation: 'işlem', definitionTr: 'Süreç', exampleSentence: 'The process takes a few minutes.', exampleSentenceTr: 'İşlem birkaç dakika sürüyor.', type: 'noun', level: 'B1' },
    { word: 'processor', turkishTranslation: 'işlemci', definitionTr: 'CPU', exampleSentence: 'This processor is very fast.', exampleSentenceTr: 'Bu işlemci çok hızlı.', type: 'noun', level: 'B1' },
    { word: 'program', turkishTranslation: 'program', definitionTr: 'Yazılım', exampleSentence: 'Run the program.', exampleSentenceTr: 'Programı çalıştırın.', type: 'noun', level: 'A1' },
];
