// src/lib/wordBankHealth.ts
// Sağlık kategorisi - 100+ kelime

import { WordData } from './wordBank';

export const healthWords: WordData[] = [
    { word: 'ache', turkishTranslation: 'ağrı', definitionTr: 'Sızı', exampleSentence: 'I have a headache.', exampleSentenceTr: 'Başım ağrıyor.', type: 'noun', level: 'A2' },
    { word: 'addiction', turkishTranslation: 'bağımlılık', definitionTr: 'Tutkunluk', exampleSentence: 'Addiction is a serious problem.', exampleSentenceTr: 'Bağımlılık ciddi bir sorun.', type: 'noun', level: 'B2' },
    { word: 'allergy', turkishTranslation: 'alerji', definitionTr: 'Hassasiyet', exampleSentence: 'I have a peanut allergy.', exampleSentenceTr: 'Fıstık alerjim var.', type: 'noun', level: 'A2' },
    { word: 'ambulance', turkishTranslation: 'ambulans', definitionTr: 'Acil yardım aracı', exampleSentence: 'Call an ambulance!', exampleSentenceTr: 'Ambulans çağır!', type: 'noun', level: 'A2' },
    { word: 'antibiotic', turkishTranslation: 'antibiyotik', definitionTr: 'Bakteri öldürücü ilaç', exampleSentence: 'Take the antibiotics daily.', exampleSentenceTr: 'Antibiyotikleri günlük alın.', type: 'noun', level: 'B1' },
    { word: 'anxiety', turkishTranslation: 'anksiyete', definitionTr: 'Kaygı bozukluğu', exampleSentence: 'She suffers from anxiety.', exampleSentenceTr: 'Anksiyete sorunu var.', type: 'noun', level: 'B1' },
    { word: 'appointment', turkishTranslation: 'randevu', definitionTr: 'Görüşme zamanı', exampleSentence: 'I have a doctor appointment.', exampleSentenceTr: 'Doktor randevum var.', type: 'noun', level: 'A2' },
    { word: 'bandage', turkishTranslation: 'bandaj', definitionTr: 'Sargı', exampleSentence: 'Put a bandage on the wound.', exampleSentenceTr: 'Yaraya bandaj sarın.', type: 'noun', level: 'A2' },
    { word: 'blood', turkishTranslation: 'kan', definitionTr: 'Vücuttaki sıvı', exampleSentence: 'I need a blood test.', exampleSentenceTr: 'Kan testi yaptırmam lazım.', type: 'noun', level: 'A1' },
    { word: 'bone', turkishTranslation: 'kemik', definitionTr: 'İskelet parçası', exampleSentence: 'He broke a bone.', exampleSentenceTr: 'Kemik kırdı.', type: 'noun', level: 'A2' },
    { word: 'brain', turkishTranslation: 'beyin', definitionTr: 'Düşünce organı', exampleSentence: 'The brain controls everything.', exampleSentenceTr: 'Beyin her şeyi kontrol eder.', type: 'noun', level: 'A2' },
    { word: 'breath', turkishTranslation: 'nefes', definitionTr: 'Soluk', exampleSentence: 'Take a deep breath.', exampleSentenceTr: 'Derin bir nefes al.', type: 'noun', level: 'A2' },
    { word: 'bruise', turkishTranslation: 'çürük', definitionTr: 'Mor leke', exampleSentence: 'I have a bruise on my arm.', exampleSentenceTr: 'Kolumda çürük var.', type: 'noun', level: 'B1' },
    { word: 'cancer', turkishTranslation: 'kanser', definitionTr: 'Kötü huylu ur', exampleSentence: 'She was diagnosed with cancer.', exampleSentenceTr: 'Kanser teşhisi konuldu.', type: 'noun', level: 'B1' },
    { word: 'capsule', turkishTranslation: 'kapsül', definitionTr: 'İlaç formu', exampleSentence: 'Take one capsule daily.', exampleSentenceTr: 'Günde bir kapsül alın.', type: 'noun', level: 'B1' },
    { word: 'checkup', turkishTranslation: 'kontrol', definitionTr: 'Muayene', exampleSentence: 'I had a health checkup.', exampleSentenceTr: 'Sağlık kontrolü yaptırdım.', type: 'noun', level: 'B1' },
    { word: 'chronic', turkishTranslation: 'kronik', definitionTr: 'Süreğen', exampleSentence: 'He has a chronic disease.', exampleSentenceTr: 'Kronik bir hastalığı var.', type: 'adjective', level: 'B2' },
    { word: 'clinic', turkishTranslation: 'klinik', definitionTr: 'Sağlık merkezi', exampleSentence: 'Visit the clinic tomorrow.', exampleSentenceTr: 'Yarın kliniğe git.', type: 'noun', level: 'A2' },
    { word: 'cold', turkishTranslation: 'soğuk algınlığı', definitionTr: 'Grip', exampleSentence: 'I caught a cold.', exampleSentenceTr: 'Soğuk algınlığına yakalandım.', type: 'noun', level: 'A1' },
    { word: 'condition', turkishTranslation: 'durum', definitionTr: 'Sağlık durumu', exampleSentence: 'His condition is stable.', exampleSentenceTr: 'Durumu stabil.', type: 'noun', level: 'B1' },
    { word: 'conscious', turkishTranslation: 'bilinçli', definitionTr: 'Farkında', exampleSentence: 'Is the patient conscious?', exampleSentenceTr: 'Hasta bilinçli mi?', type: 'adjective', level: 'B1' },
    { word: 'contagious', turkishTranslation: 'bulaşıcı', definitionTr: 'Geçebilen', exampleSentence: 'The disease is contagious.', exampleSentenceTr: 'Hastalık bulaşıcı.', type: 'adjective', level: 'B2' },
    { word: 'cough', turkishTranslation: 'öksürmek', definitionTr: 'Hava atmak', exampleSentence: 'I have a bad cough.', exampleSentenceTr: 'Kötü bir öksürüğüm var.', type: 'verb', level: 'A2' },
    { word: 'cure', turkishTranslation: 'tedavi', definitionTr: 'İyileştirme', exampleSentence: 'Is there a cure for this?', exampleSentenceTr: 'Bunun tedavisi var mı?', type: 'noun', level: 'B1' },
    { word: 'dentist', turkishTranslation: 'diş hekimi', definitionTr: 'Diş doktoru', exampleSentence: 'I have to see the dentist.', exampleSentenceTr: 'Diş hekimine gitmem lazım.', type: 'noun', level: 'A1' },
    { word: 'depression', turkishTranslation: 'depresyon', definitionTr: 'Ruhsal çöküntü', exampleSentence: 'Depression is treatable.', exampleSentenceTr: 'Depresyon tedavi edilebilir.', type: 'noun', level: 'B1' },
    { word: 'diabetes', turkishTranslation: 'diyabet', definitionTr: 'Şeker hastalığı', exampleSentence: 'She has diabetes.', exampleSentenceTr: 'Diyabet hastası.', type: 'noun', level: 'B1' },
    { word: 'diagnose', turkishTranslation: 'teşhis koymak', definitionTr: 'Hastalık belirlemek', exampleSentence: 'The doctor diagnosed the illness.', exampleSentenceTr: 'Doktor hastalığı teşhis etti.', type: 'verb', level: 'B2' },
    { word: 'diet', turkishTranslation: 'diyet', definitionTr: 'Beslenme düzeni', exampleSentence: 'Follow a healthy diet.', exampleSentenceTr: 'Sağlıklı bir diyet uygula.', type: 'noun', level: 'A2' },
    { word: 'disease', turkishTranslation: 'hastalık', definitionTr: 'Rahatsızlık', exampleSentence: 'Heart disease is common.', exampleSentenceTr: 'Kalp hastalığı yaygın.', type: 'noun', level: 'A2' },
    { word: 'dizzy', turkishTranslation: 'baş dönmesi', definitionTr: 'Sersemlik', exampleSentence: 'I feel dizzy.', exampleSentenceTr: 'Başım dönüyor.', type: 'adjective', level: 'B1' },
    { word: 'doctor', turkishTranslation: 'doktor', definitionTr: 'Hekim', exampleSentence: 'See a doctor immediately.', exampleSentenceTr: 'Hemen doktora görün.', type: 'noun', level: 'A1' },
    { word: 'dose', turkishTranslation: 'doz', definitionTr: 'İlaç miktarı', exampleSentence: 'What is the correct dose?', exampleSentenceTr: 'Doğru doz nedir?', type: 'noun', level: 'B1' },
    { word: 'drug', turkishTranslation: 'ilaç', definitionTr: 'Tedavi maddesi', exampleSentence: 'This drug has side effects.', exampleSentenceTr: 'Bu ilacın yan etkileri var.', type: 'noun', level: 'A2' },
    { word: 'emergency', turkishTranslation: 'acil', definitionTr: 'İvedi durum', exampleSentence: 'This is an emergency!', exampleSentenceTr: 'Bu bir acil durum!', type: 'noun', level: 'A2' },
    { word: 'examine', turkishTranslation: 'muayene etmek', definitionTr: 'İncelemek', exampleSentence: 'The doctor examined me.', exampleSentenceTr: 'Doktor beni muayene etti.', type: 'verb', level: 'B1' },
    { word: 'exercise', turkishTranslation: 'egzersiz', definitionTr: 'Spor', exampleSentence: 'Exercise is important for health.', exampleSentenceTr: 'Egzersiz sağlık için önemli.', type: 'noun', level: 'A2' },
    { word: 'exhausted', turkishTranslation: 'bitkin', definitionTr: 'Çok yorgun', exampleSentence: 'I am completely exhausted.', exampleSentenceTr: 'Tamamen bitkinim.', type: 'adjective', level: 'B1' },
    { word: 'faint', turkishTranslation: 'bayılmak', definitionTr: 'Kendinden geçmek', exampleSentence: 'She felt faint.', exampleSentenceTr: 'Bayılacak gibi hissetti.', type: 'verb', level: 'B1' },
    { word: 'fatigue', turkishTranslation: 'yorgunluk', definitionTr: 'Bitkinlik', exampleSentence: 'Chronic fatigue is exhausting.', exampleSentenceTr: 'Kronik yorgunluk yıpratıcı.', type: 'noun', level: 'B2' },
    { word: 'fever', turkishTranslation: 'ateş', definitionTr: 'Yüksek vücut ısısı', exampleSentence: 'He has a high fever.', exampleSentenceTr: 'Yüksek ateşi var.', type: 'noun', level: 'A2' },
    { word: 'fit', turkishTranslation: 'formda', definitionTr: 'Sağlıklı', exampleSentence: 'Stay fit and healthy.', exampleSentenceTr: 'Formda ve sağlıklı kal.', type: 'adjective', level: 'A2' },
    { word: 'flu', turkishTranslation: 'grip', definitionTr: 'Nezle', exampleSentence: 'I have the flu.', exampleSentenceTr: 'Grip oldum.', type: 'noun', level: 'A2' },
    { word: 'fracture', turkishTranslation: 'kırık', definitionTr: 'Kemik kırığı', exampleSentence: 'He has a bone fracture.', exampleSentenceTr: 'Kemik kırığı var.', type: 'noun', level: 'B1' },
    { word: 'heal', turkishTranslation: 'iyileşmek', definitionTr: 'Düzelmek', exampleSentence: 'The wound will heal soon.', exampleSentenceTr: 'Yara yakında iyileşecek.', type: 'verb', level: 'B1' },
    { word: 'health', turkishTranslation: 'sağlık', definitionTr: 'Vücut durumu', exampleSentence: 'Health is wealth.', exampleSentenceTr: 'Sağlık en büyük zenginlik.', type: 'noun', level: 'A1' },
    { word: 'healthy', turkishTranslation: 'sağlıklı', definitionTr: 'İyi durumda', exampleSentence: 'Eat healthy food.', exampleSentenceTr: 'Sağlıklı yiyecekler ye.', type: 'adjective', level: 'A1' },
    { word: 'heart', turkishTranslation: 'kalp', definitionTr: 'Pompa organı', exampleSentence: 'The heart pumps blood.', exampleSentenceTr: 'Kalp kan pompalar.', type: 'noun', level: 'A1' },
    { word: 'hospital', turkishTranslation: 'hastane', definitionTr: 'Sağlık kurumu', exampleSentence: 'She was taken to the hospital.', exampleSentenceTr: 'Hastaneye kaldırıldı.', type: 'noun', level: 'A1' },
    { word: 'hurt', turkishTranslation: 'acımak', definitionTr: 'Ağrı vermek', exampleSentence: 'My back hurts.', exampleSentenceTr: 'Sırtım ağrıyor.', type: 'verb', level: 'A1' },
    { word: 'immune', turkishTranslation: 'bağışık', definitionTr: 'Korumalı', exampleSentence: 'Build your immune system.', exampleSentenceTr: 'Bağışıklık sisteminizi güçlendirin.', type: 'adjective', level: 'B1' },
    { word: 'infection', turkishTranslation: 'enfeksiyon', definitionTr: 'Mikrop bulaşması', exampleSentence: 'He has an ear infection.', exampleSentenceTr: 'Kulak enfeksiyonu var.', type: 'noun', level: 'B1' },
    { word: 'inject', turkishTranslation: 'enjekte etmek', definitionTr: 'İğne yapmak', exampleSentence: 'The nurse will inject the vaccine.', exampleSentenceTr: 'Hemşire aşıyı enjekte edecek.', type: 'verb', level: 'B1' },
    { word: 'injury', turkishTranslation: 'yaralanma', definitionTr: 'Hasar', exampleSentence: 'He recovered from the injury.', exampleSentenceTr: 'Yaralanmadan iyileşti.', type: 'noun', level: 'B1' },
    { word: 'insurance', turkishTranslation: 'sigorta', definitionTr: 'Sağlık güvencesi', exampleSentence: 'Do you have health insurance?', exampleSentenceTr: 'Sağlık sigortanız var mı?', type: 'noun', level: 'B1' },
    { word: 'intensive', turkishTranslation: 'yoğun', definitionTr: 'Güçlü', exampleSentence: 'He is in intensive care.', exampleSentenceTr: 'Yoğun bakımda.', type: 'adjective', level: 'B2' },
    { word: 'laboratory', turkishTranslation: 'laboratuvar', definitionTr: 'Deney yeri', exampleSentence: 'Blood tests are done in the laboratory.', exampleSentenceTr: 'Kan testleri laboratuvarda yapılır.', type: 'noun', level: 'B1' },
    { word: 'lung', turkishTranslation: 'akciğer', definitionTr: 'Solunum organı', exampleSentence: 'Smoking damages the lungs.', exampleSentenceTr: 'Sigara akciğerlere zarar verir.', type: 'noun', level: 'A2' },
    { word: 'medical', turkishTranslation: 'tıbbi', definitionTr: 'Sağlıkla ilgili', exampleSentence: 'She needs medical attention.', exampleSentenceTr: 'Tıbbi müdahaleye ihtiyacı var.', type: 'adjective', level: 'A2' },
    { word: 'medication', turkishTranslation: 'ilaç tedavisi', definitionTr: 'İlaç kullanımı', exampleSentence: 'Are you on any medication?', exampleSentenceTr: 'Herhangi bir ilaç kullanıyor musunuz?', type: 'noun', level: 'B1' },
    { word: 'medicine', turkishTranslation: 'ilaç', definitionTr: 'Tedavi maddesi', exampleSentence: 'Take your medicine on time.', exampleSentenceTr: 'İlacınızı zamanında alın.', type: 'noun', level: 'A1' },
    { word: 'mental', turkishTranslation: 'zihinsel', definitionTr: 'Akılla ilgili', exampleSentence: 'Mental health is important.', exampleSentenceTr: 'Zihinsel sağlık önemli.', type: 'adjective', level: 'B1' },
    { word: 'muscle', turkishTranslation: 'kas', definitionTr: 'Hareket dokusu', exampleSentence: 'I pulled a muscle.', exampleSentenceTr: 'Kasımı çektim.', type: 'noun', level: 'A2' },
    { word: 'nausea', turkishTranslation: 'mide bulantısı', definitionTr: 'Kusma hissi', exampleSentence: 'I feel nausea.', exampleSentenceTr: 'Mide bulantım var.', type: 'noun', level: 'B2' },
    { word: 'nerve', turkishTranslation: 'sinir', definitionTr: 'Sinir sistemi parçası', exampleSentence: 'The nerve was damaged.', exampleSentenceTr: 'Sinir hasar gördü.', type: 'noun', level: 'B1' },
    { word: 'nurse', turkishTranslation: 'hemşire', definitionTr: 'Sağlık bakıcısı', exampleSentence: 'The nurse took my blood.', exampleSentenceTr: 'Hemşire kanımı aldı.', type: 'noun', level: 'A1' },
    { word: 'nutrition', turkishTranslation: 'beslenme', definitionTr: 'Gıda alımı', exampleSentence: 'Good nutrition is essential.', exampleSentenceTr: 'İyi beslenme çok önemli.', type: 'noun', level: 'B1' },
    { word: 'obese', turkishTranslation: 'obez', definitionTr: 'Aşırı kilolu', exampleSentence: 'Obesity is a health risk.', exampleSentenceTr: 'Obezite sağlık riski.', type: 'adjective', level: 'B2' },
    { word: 'operation', turkishTranslation: 'ameliyat', definitionTr: 'Cerrahi müdahale', exampleSentence: 'The operation was successful.', exampleSentenceTr: 'Ameliyat başarılı geçti.', type: 'noun', level: 'A2' },
    { word: 'organ', turkishTranslation: 'organ', definitionTr: 'Vücut parçası', exampleSentence: 'The heart is a vital organ.', exampleSentenceTr: 'Kalp hayati bir organ.', type: 'noun', level: 'B1' },
    { word: 'pain', turkishTranslation: 'ağrı', definitionTr: 'Acı', exampleSentence: 'I have chest pain.', exampleSentenceTr: 'Göğüs ağrım var.', type: 'noun', level: 'A2' },
    { word: 'patient', turkishTranslation: 'hasta', definitionTr: 'Tedavi gören', exampleSentence: 'The patient is recovering.', exampleSentenceTr: 'Hasta iyileşiyor.', type: 'noun', level: 'A2' },
    { word: 'pharmacy', turkishTranslation: 'eczane', definitionTr: 'İlaç satış yeri', exampleSentence: 'Buy medicine at the pharmacy.', exampleSentenceTr: 'İlacı eczaneden alın.', type: 'noun', level: 'A2' },
    { word: 'physical', turkishTranslation: 'fiziksel', definitionTr: 'Bedensel', exampleSentence: 'Physical activity is important.', exampleSentenceTr: 'Fiziksel aktivite önemli.', type: 'adjective', level: 'A2' },
    { word: 'pill', turkishTranslation: 'hap', definitionTr: 'Tablet ilaç', exampleSentence: 'Take one pill before bed.', exampleSentenceTr: 'Yatmadan önce bir hap alın.', type: 'noun', level: 'A2' },
    { word: 'pregnant', turkishTranslation: 'hamile', definitionTr: 'Gebe', exampleSentence: 'She is three months pregnant.', exampleSentenceTr: 'Üç aylık hamile.', type: 'adjective', level: 'A2' },
    { word: 'prescription', turkishTranslation: 'reçete', definitionTr: 'İlaç yazısı', exampleSentence: 'You need a prescription for this.', exampleSentenceTr: 'Bunun için reçete gerekiyor.', type: 'noun', level: 'B1' },
    { word: 'pressure', turkishTranslation: 'tansiyon', definitionTr: 'Kan basıncı', exampleSentence: 'Check your blood pressure.', exampleSentenceTr: 'Tansiyonunuzu ölçün.', type: 'noun', level: 'A2' },
    { word: 'prevent', turkishTranslation: 'önlemek', definitionTr: 'Engellemek', exampleSentence: 'Prevent disease with vaccines.', exampleSentenceTr: 'Aşılarla hastalığı önleyin.', type: 'verb', level: 'B1' },
    { word: 'pulse', turkishTranslation: 'nabız', definitionTr: 'Kalp atışı', exampleSentence: 'Check the patient\'s pulse.', exampleSentenceTr: 'Hastanın nabzını kontrol edin.', type: 'noun', level: 'B1' },
    { word: 'recover', turkishTranslation: 'iyileşmek', definitionTr: 'Düzelmek', exampleSentence: 'He is recovering well.', exampleSentenceTr: 'İyi bir şekilde iyileşiyor.', type: 'verb', level: 'B1' },
    { word: 'relax', turkishTranslation: 'rahatlamak', definitionTr: 'Gevşemek', exampleSentence: 'Try to relax and rest.', exampleSentenceTr: 'Rahatlamaya ve dinlenmeye çalış.', type: 'verb', level: 'A2' },
    { word: 'remedy', turkishTranslation: 'çare', definitionTr: 'Tedavi yolu', exampleSentence: 'Try this home remedy.', exampleSentenceTr: 'Bu ev ilacını deneyin.', type: 'noun', level: 'B2' },
    { word: 'scan', turkishTranslation: 'tarama', definitionTr: 'Görüntüleme', exampleSentence: 'I need a CT scan.', exampleSentenceTr: 'Tomografi çektirmem lazım.', type: 'noun', level: 'B1' },
    { word: 'sick', turkishTranslation: 'hasta', definitionTr: 'Rahatsız', exampleSentence: 'I feel sick today.', exampleSentenceTr: 'Bugün kendimi hasta hissediyorum.', type: 'adjective', level: 'A1' },
    { word: 'sneeze', turkishTranslation: 'hapşırmak', definitionTr: 'Aks yapmak', exampleSentence: 'Cover your mouth when you sneeze.', exampleSentenceTr: 'Hapşırırken ağzınızı kapatın.', type: 'verb', level: 'A2' },
    { word: 'sore', turkishTranslation: 'ağrılı', definitionTr: 'Acıyan', exampleSentence: 'I have a sore throat.', exampleSentenceTr: 'Boğazım ağrıyor.', type: 'adjective', level: 'A2' },
    { word: 'specialist', turkishTranslation: 'uzman', definitionTr: 'Alan doktoru', exampleSentence: 'See a heart specialist.', exampleSentenceTr: 'Kalp uzmanına görünün.', type: 'noun', level: 'B1' },
    { word: 'sprain', turkishTranslation: 'burkmak', definitionTr: 'İncinmek', exampleSentence: 'I sprained my ankle.', exampleSentenceTr: 'Ayak bileğimi burktum.', type: 'verb', level: 'B1' },
    { word: 'stomach', turkishTranslation: 'mide', definitionTr: 'Sindirim organı', exampleSentence: 'My stomach hurts.', exampleSentenceTr: 'Midem ağrıyor.', type: 'noun', level: 'A1' },
    { word: 'stress', turkishTranslation: 'stres', definitionTr: 'Gerginlik', exampleSentence: 'Stress affects your health.', exampleSentenceTr: 'Stres sağlığınızı etkiler.', type: 'noun', level: 'A2' },
    { word: 'surgery', turkishTranslation: 'cerrahi', definitionTr: 'Ameliyat', exampleSentence: 'He needs surgery.', exampleSentenceTr: 'Ameliyata ihtiyacı var.', type: 'noun', level: 'B1' },
    { word: 'swallow', turkishTranslation: 'yutmak', definitionTr: 'İçmek', exampleSentence: 'Swallow the pill with water.', exampleSentenceTr: 'Hapı suyla yutun.', type: 'verb', level: 'A2' },
    { word: 'symptom', turkishTranslation: 'belirti', definitionTr: 'Hastalık işareti', exampleSentence: 'What are your symptoms?', exampleSentenceTr: 'Belirtileriniz neler?', type: 'noun', level: 'B1' },
    { word: 'temperature', turkishTranslation: 'ateş', definitionTr: 'Vücut ısısı', exampleSentence: 'Check your temperature.', exampleSentenceTr: 'Ateşinizi ölçün.', type: 'noun', level: 'A2' },
    { word: 'therapy', turkishTranslation: 'terapi', definitionTr: 'Tedavi yöntemi', exampleSentence: 'She started therapy.', exampleSentenceTr: 'Terapiye başladı.', type: 'noun', level: 'B1' },
    { word: 'tissue', turkishTranslation: 'doku', definitionTr: 'Hücre grubu', exampleSentence: 'The tissue is damaged.', exampleSentenceTr: 'Doku hasar görmüş.', type: 'noun', level: 'B1' },
    { word: 'treat', turkishTranslation: 'tedavi etmek', definitionTr: 'İyileştirmek', exampleSentence: 'How do you treat this condition?', exampleSentenceTr: 'Bu durumu nasıl tedavi ediyorsunuz?', type: 'verb', level: 'B1' },
    { word: 'treatment', turkishTranslation: 'tedavi', definitionTr: 'İyileştirme süreci', exampleSentence: 'What treatment is best?', exampleSentenceTr: 'En iyi tedavi hangisi?', type: 'noun', level: 'A2' },
    { word: 'unconscious', turkishTranslation: 'bilinçsiz', definitionTr: 'Bayık', exampleSentence: 'He was found unconscious.', exampleSentenceTr: 'Bilinçsiz halde bulundu.', type: 'adjective', level: 'B1' },
    { word: 'vaccine', turkishTranslation: 'aşı', definitionTr: 'Koruyucu ilaç', exampleSentence: 'Get your flu vaccine.', exampleSentenceTr: 'Grip aşınızı yaptırın.', type: 'noun', level: 'A2' },
    { word: 'virus', turkishTranslation: 'virüs', definitionTr: 'Hastalık yapan mikrop', exampleSentence: 'The virus spreads quickly.', exampleSentenceTr: 'Virüs hızla yayılıyor.', type: 'noun', level: 'A2' },
    { word: 'vitamin', turkishTranslation: 'vitamin', definitionTr: 'Besin maddesi', exampleSentence: 'Take your vitamins daily.', exampleSentenceTr: 'Vitaminlerinizi günlük alın.', type: 'noun', level: 'A2' },
    { word: 'weight', turkishTranslation: 'kilo', definitionTr: 'Vücut ağırlığı', exampleSentence: 'Watch your weight.', exampleSentenceTr: 'Kilonuza dikkat edin.', type: 'noun', level: 'A2' },
    { word: 'wellness', turkishTranslation: 'sağlıklılık', definitionTr: 'İyi olma durumu', exampleSentence: 'Focus on your wellness.', exampleSentenceTr: 'Sağlığınıza odaklanın.', type: 'noun', level: 'B1' },
    { word: 'wound', turkishTranslation: 'yara', definitionTr: 'Kesik', exampleSentence: 'Clean the wound carefully.', exampleSentenceTr: 'Yarayı dikkatle temizleyin.', type: 'noun', level: 'A2' },
];
