// src/lib/wordBank.ts
// Hardcoded word bank with 100+ words per category

export interface WordData {
    word: string;
    turkishTranslation: string;
    definitionTr: string;
    exampleSentence: string;
    exampleSentenceTr: string;
    type: string;
    level: string;
}

// ==================== GENEL (General) ====================
export const generalWords: WordData[] = [
    { word: 'ability', turkishTranslation: 'yetenek', definitionTr: 'Bir şeyi yapabilme kapasitesi', exampleSentence: 'She has the ability to learn languages quickly.', exampleSentenceTr: 'Dilleri hızlı öğrenme yeteneğine sahip.', type: 'noun', level: 'A2' },
    { word: 'accept', turkishTranslation: 'kabul etmek', definitionTr: 'Bir şeyi onaylamak veya almak', exampleSentence: 'I accept your invitation.', exampleSentenceTr: 'Davetini kabul ediyorum.', type: 'verb', level: 'A2' },
    { word: 'achieve', turkishTranslation: 'başarmak', definitionTr: 'Bir hedefe ulaşmak', exampleSentence: 'He achieved his goal of becoming a doctor.', exampleSentenceTr: 'Doktor olma hedefine ulaştı.', type: 'verb', level: 'B1' },
    { word: 'actually', turkishTranslation: 'aslında', definitionTr: 'Gerçekte, doğrusu', exampleSentence: 'Actually, I prefer staying home.', exampleSentenceTr: 'Aslında evde kalmayı tercih ederim.', type: 'adverb', level: 'A2' },
    { word: 'advantage', turkishTranslation: 'avantaj', definitionTr: 'Olumlu durum veya fayda', exampleSentence: 'Speaking English is a great advantage.', exampleSentenceTr: 'İngilizce bilmek büyük bir avantaj.', type: 'noun', level: 'B1' },
    { word: 'advice', turkishTranslation: 'tavsiye', definitionTr: 'Öğüt, öneri', exampleSentence: 'Can I give you some advice?', exampleSentenceTr: 'Sana bir tavsiye verebilir miyim?', type: 'noun', level: 'A2' },
    { word: 'affect', turkishTranslation: 'etkilemek', definitionTr: 'Bir değişikliğe neden olmak', exampleSentence: 'The weather affects my mood.', exampleSentenceTr: 'Hava durumu ruh halimi etkiler.', type: 'verb', level: 'B1' },
    { word: 'agree', turkishTranslation: 'katılmak', definitionTr: 'Aynı fikirde olmak', exampleSentence: 'I agree with your opinion.', exampleSentenceTr: 'Fikrine katılıyorum.', type: 'verb', level: 'A2' },
    { word: 'allow', turkishTranslation: 'izin vermek', definitionTr: 'Müsaade etmek', exampleSentence: 'My parents allow me to stay up late.', exampleSentenceTr: 'Ailem geç yatmama izin veriyor.', type: 'verb', level: 'A2' },
    { word: 'amazing', turkishTranslation: 'harika', definitionTr: 'Şaşırtıcı derecede iyi', exampleSentence: 'The view from here is amazing.', exampleSentenceTr: 'Buradan manzara harika.', type: 'adjective', level: 'A2' },
    { word: 'amount', turkishTranslation: 'miktar', definitionTr: 'Toplam sayı veya ölçü', exampleSentence: 'A large amount of water is wasted daily.', exampleSentenceTr: 'Her gün büyük miktarda su israf ediliyor.', type: 'noun', level: 'B1' },
    { word: 'announce', turkishTranslation: 'duyurmak', definitionTr: 'Resmi olarak bildirmek', exampleSentence: 'They announced the winner yesterday.', exampleSentenceTr: 'Dün kazananı duyurdular.', type: 'verb', level: 'B1' },
    { word: 'anxious', turkishTranslation: 'endişeli', definitionTr: 'Kaygılı, tedirgin', exampleSentence: 'She felt anxious about the exam.', exampleSentenceTr: 'Sınav hakkında endişeliydi.', type: 'adjective', level: 'B1' },
    { word: 'appear', turkishTranslation: 'görünmek', definitionTr: 'Ortaya çıkmak', exampleSentence: 'The sun appeared from behind the clouds.', exampleSentenceTr: 'Güneş bulutların arkasından göründü.', type: 'verb', level: 'A2' },
    { word: 'approach', turkishTranslation: 'yaklaşmak', definitionTr: 'Birine veya bir yere yaklaşmak', exampleSentence: 'We approached the house carefully.', exampleSentenceTr: 'Eve dikkatli bir şekilde yaklaştık.', type: 'verb', level: 'B1' },
    { word: 'appropriate', turkishTranslation: 'uygun', definitionTr: 'Doğru, yerinde', exampleSentence: 'Is this dress appropriate for the party?', exampleSentenceTr: 'Bu elbise parti için uygun mu?', type: 'adjective', level: 'B1' },
    { word: 'arrange', turkishTranslation: 'düzenlemek', definitionTr: 'Organize etmek, ayarlamak', exampleSentence: 'Can you arrange a meeting for tomorrow?', exampleSentenceTr: 'Yarın için bir toplantı ayarlayabilir misin?', type: 'verb', level: 'B1' },
    { word: 'attempt', turkishTranslation: 'deneme', definitionTr: 'Girişim, teşebbüs', exampleSentence: 'This is my first attempt at cooking.', exampleSentenceTr: 'Bu benim ilk yemek yapma denemem.', type: 'noun', level: 'B1' },
    { word: 'attention', turkishTranslation: 'dikkat', definitionTr: 'Odaklanma, ilgi', exampleSentence: 'Pay attention to the teacher.', exampleSentenceTr: 'Öğretmene dikkat et.', type: 'noun', level: 'A2' },
    { word: 'attitude', turkishTranslation: 'tutum', definitionTr: 'Davranış biçimi', exampleSentence: 'She has a positive attitude.', exampleSentenceTr: 'Olumlu bir tutumu var.', type: 'noun', level: 'B1' },
    { word: 'available', turkishTranslation: 'mevcut', definitionTr: 'Ulaşılabilir, müsait', exampleSentence: 'Is this book available in Turkish?', exampleSentenceTr: 'Bu kitap Türkçe mevcut mu?', type: 'adjective', level: 'A2' },
    { word: 'avoid', turkishTranslation: 'kaçınmak', definitionTr: 'Uzak durmak', exampleSentence: 'I try to avoid junk food.', exampleSentenceTr: 'Abur cuburdan kaçınmaya çalışıyorum.', type: 'verb', level: 'B1' },
    { word: 'aware', turkishTranslation: 'farkında', definitionTr: 'Bilincinde olmak', exampleSentence: 'Are you aware of the risks?', exampleSentenceTr: 'Risklerin farkında mısın?', type: 'adjective', level: 'B1' },
    { word: 'background', turkishTranslation: 'arka plan', definitionTr: 'Geçmiş, zemin', exampleSentence: 'What is your educational background?', exampleSentenceTr: 'Eğitim geçmişin nedir?', type: 'noun', level: 'B1' },
    { word: 'balance', turkishTranslation: 'denge', definitionTr: 'Eşit dağılım', exampleSentence: 'It is important to keep a work-life balance.', exampleSentenceTr: 'İş-yaşam dengesi korumak önemlidir.', type: 'noun', level: 'B1' },
    { word: 'basically', turkishTranslation: 'temelde', definitionTr: 'Esas olarak', exampleSentence: 'Basically, I agree with you.', exampleSentenceTr: 'Temelde sana katılıyorum.', type: 'adverb', level: 'B1' },
    { word: 'behavior', turkishTranslation: 'davranış', definitionTr: 'Hareket tarzı', exampleSentence: 'His behavior was unacceptable.', exampleSentenceTr: 'Davranışı kabul edilemezdi.', type: 'noun', level: 'B1' },
    { word: 'believe', turkishTranslation: 'inanmak', definitionTr: 'Güvenmek, kabul etmek', exampleSentence: 'I believe you can do it.', exampleSentenceTr: 'Yapabileceğine inanıyorum.', type: 'verb', level: 'A2' },
    { word: 'benefit', turkishTranslation: 'fayda', definitionTr: 'Yararlı sonuç', exampleSentence: 'Exercise has many health benefits.', exampleSentenceTr: 'Egzersizin birçok sağlık faydası var.', type: 'noun', level: 'B1' },
    { word: 'besides', turkishTranslation: 'ayrıca', definitionTr: 'Bunun yanı sıra', exampleSentence: 'Besides English, I speak French.', exampleSentenceTr: 'İngilizce yanı sıra Fransızca da konuşurum.', type: 'preposition', level: 'B1' },
    { word: 'beyond', turkishTranslation: 'ötesinde', definitionTr: 'Daha ileride', exampleSentence: 'The village is beyond those mountains.', exampleSentenceTr: 'Köy o dağların ötesinde.', type: 'preposition', level: 'B1' },
    { word: 'blame', turkishTranslation: 'suçlamak', definitionTr: 'Sorumluluk yüklemek', exampleSentence: 'Do not blame others for your mistakes.', exampleSentenceTr: 'Hatalarından dolayı başkalarını suçlama.', type: 'verb', level: 'B1' },
    { word: 'bother', turkishTranslation: 'rahatsız etmek', definitionTr: 'Canını sıkmak', exampleSentence: 'Sorry to bother you.', exampleSentenceTr: 'Rahatsız ettiğim için özür dilerim.', type: 'verb', level: 'B1' },
    { word: 'brief', turkishTranslation: 'kısa', definitionTr: 'Az süren', exampleSentence: 'I will give a brief explanation.', exampleSentenceTr: 'Kısa bir açıklama yapacağım.', type: 'adjective', level: 'B1' },
    { word: 'brilliant', turkishTranslation: 'parlak', definitionTr: 'Çok zeki veya harika', exampleSentence: 'That is a brilliant idea!', exampleSentenceTr: 'Bu harika bir fikir!', type: 'adjective', level: 'B1' },
    { word: 'capable', turkishTranslation: 'yetenekli', definitionTr: 'Yapabilecek güçte', exampleSentence: 'She is capable of great things.', exampleSentenceTr: 'Büyük işler yapabilecek yetenekte.', type: 'adjective', level: 'B1' },
    { word: 'careful', turkishTranslation: 'dikkatli', definitionTr: 'Özen gösteren', exampleSentence: 'Be careful when crossing the street.', exampleSentenceTr: 'Karşıya geçerken dikkatli ol.', type: 'adjective', level: 'A2' },
    { word: 'certain', turkishTranslation: 'kesin', definitionTr: 'Emin, belli', exampleSentence: 'I am certain about my decision.', exampleSentenceTr: 'Kararımdan eminim.', type: 'adjective', level: 'B1' },
    { word: 'challenge', turkishTranslation: 'zorluk', definitionTr: 'Meydan okuma', exampleSentence: 'Learning a new language is a challenge.', exampleSentenceTr: 'Yeni bir dil öğrenmek bir zorluktur.', type: 'noun', level: 'B1' },
    { word: 'chance', turkishTranslation: 'şans', definitionTr: 'Olasılık, fırsat', exampleSentence: 'Give me a chance to explain.', exampleSentenceTr: 'Bana açıklama şansı ver.', type: 'noun', level: 'A2' },
    { word: 'character', turkishTranslation: 'karakter', definitionTr: 'Kişilik özellikleri', exampleSentence: 'He has a strong character.', exampleSentenceTr: 'Güçlü bir karaktere sahip.', type: 'noun', level: 'B1' },
    { word: 'choice', turkishTranslation: 'seçim', definitionTr: 'Tercih hakkı', exampleSentence: 'You have a choice to make.', exampleSentenceTr: 'Yapman gereken bir seçim var.', type: 'noun', level: 'A2' },
    { word: 'claim', turkishTranslation: 'iddia etmek', definitionTr: 'İleri sürmek', exampleSentence: 'He claims to be innocent.', exampleSentenceTr: 'Masum olduğunu iddia ediyor.', type: 'verb', level: 'B1' },
    { word: 'clear', turkishTranslation: 'açık', definitionTr: 'Net, anlaşılır', exampleSentence: 'The instructions are clear.', exampleSentenceTr: 'Talimatlar açık.', type: 'adjective', level: 'A2' },
    { word: 'comfortable', turkishTranslation: 'rahat', definitionTr: 'Konforlu', exampleSentence: 'This chair is very comfortable.', exampleSentenceTr: 'Bu sandalye çok rahat.', type: 'adjective', level: 'A2' },
    { word: 'comment', turkishTranslation: 'yorum', definitionTr: 'Görüş, düşünce', exampleSentence: 'Do you have any comments?', exampleSentenceTr: 'Herhangi bir yorumun var mı?', type: 'noun', level: 'B1' },
    { word: 'commit', turkishTranslation: 'taahhüt etmek', definitionTr: 'Söz vermek', exampleSentence: 'I commit to finishing this project.', exampleSentenceTr: 'Bu projeyi bitirmeyi taahhüt ediyorum.', type: 'verb', level: 'B1' },
    { word: 'common', turkishTranslation: 'yaygın', definitionTr: 'Sık rastlanan', exampleSentence: 'This is a common mistake.', exampleSentenceTr: 'Bu yaygın bir hata.', type: 'adjective', level: 'A2' },
    { word: 'communicate', turkishTranslation: 'iletişim kurmak', definitionTr: 'Bilgi alışverişinde bulunmak', exampleSentence: 'It is important to communicate clearly.', exampleSentenceTr: 'Açık iletişim kurmak önemlidir.', type: 'verb', level: 'B1' },
    { word: 'community', turkishTranslation: 'topluluk', definitionTr: 'Bir arada yaşayan grup', exampleSentence: 'Our community is very supportive.', exampleSentenceTr: 'Topluluğumuz çok destekleyici.', type: 'noun', level: 'B1' },
    { word: 'compare', turkishTranslation: 'karşılaştırmak', definitionTr: 'Benzerlik ve farklılıkları incelemek', exampleSentence: 'Compare these two products.', exampleSentenceTr: 'Bu iki ürünü karşılaştır.', type: 'verb', level: 'B1' },
    { word: 'compete', turkishTranslation: 'yarışmak', definitionTr: 'Rekabet etmek', exampleSentence: 'Athletes compete in the Olympics.', exampleSentenceTr: 'Sporcular Olimpiyatlarda yarışır.', type: 'verb', level: 'B1' },
    { word: 'complain', turkishTranslation: 'şikayet etmek', definitionTr: 'Memnuniyetsizlik bildirmek', exampleSentence: 'He always complains about the weather.', exampleSentenceTr: 'Her zaman havadan şikayet eder.', type: 'verb', level: 'B1' },
    { word: 'complete', turkishTranslation: 'tamamlamak', definitionTr: 'Bitirmek', exampleSentence: 'Please complete the form.', exampleSentenceTr: 'Lütfen formu tamamlayın.', type: 'verb', level: 'A2' },
    { word: 'complex', turkishTranslation: 'karmaşık', definitionTr: 'Anlaşılması güç', exampleSentence: 'This is a complex problem.', exampleSentenceTr: 'Bu karmaşık bir problem.', type: 'adjective', level: 'B1' },
    { word: 'concentrate', turkishTranslation: 'konsantre olmak', definitionTr: 'Odaklanmak', exampleSentence: 'I cannot concentrate with this noise.', exampleSentenceTr: 'Bu gürültüyle konsantre olamıyorum.', type: 'verb', level: 'B1' },
    { word: 'concern', turkishTranslation: 'endişe', definitionTr: 'Kaygı, ilgi', exampleSentence: 'Your safety is our main concern.', exampleSentenceTr: 'Güvenliğiniz ana endişemiz.', type: 'noun', level: 'B1' },
    { word: 'condition', turkishTranslation: 'durum', definitionTr: 'Koşul, hal', exampleSentence: 'The car is in good condition.', exampleSentenceTr: 'Araba iyi durumda.', type: 'noun', level: 'B1' },
    { word: 'confident', turkishTranslation: 'kendine güvenen', definitionTr: 'Özgüvenli', exampleSentence: 'She is confident about her abilities.', exampleSentenceTr: 'Yetenekleri konusunda kendine güveniyor.', type: 'adjective', level: 'B1' },
    { word: 'confirm', turkishTranslation: 'onaylamak', definitionTr: 'Doğrulamak', exampleSentence: 'Please confirm your reservation.', exampleSentenceTr: 'Lütfen rezervasyonunuzu onaylayın.', type: 'verb', level: 'B1' },
    { word: 'confuse', turkishTranslation: 'karıştırmak', definitionTr: 'Şaşırtmak', exampleSentence: 'Do not confuse these two words.', exampleSentenceTr: 'Bu iki kelimeyi karıştırma.', type: 'verb', level: 'B1' },
    { word: 'connect', turkishTranslation: 'bağlamak', definitionTr: 'Birleştirmek', exampleSentence: 'Connect the cable to the computer.', exampleSentenceTr: 'Kabloyu bilgisayara bağla.', type: 'verb', level: 'A2' },
    { word: 'consider', turkishTranslation: 'düşünmek', definitionTr: 'Dikkate almak', exampleSentence: 'Please consider my offer.', exampleSentenceTr: 'Lütfen teklifimi düşünün.', type: 'verb', level: 'B1' },
    { word: 'consist', turkishTranslation: 'oluşmak', definitionTr: 'Meydana gelmek', exampleSentence: 'The team consists of five members.', exampleSentenceTr: 'Takım beş üyeden oluşuyor.', type: 'verb', level: 'B1' },
    { word: 'constant', turkishTranslation: 'sürekli', definitionTr: 'Değişmeyen', exampleSentence: 'There is constant noise here.', exampleSentenceTr: 'Burada sürekli gürültü var.', type: 'adjective', level: 'B1' },
    { word: 'contain', turkishTranslation: 'içermek', definitionTr: 'Kapsamak', exampleSentence: 'This box contains old photos.', exampleSentenceTr: 'Bu kutu eski fotoğraflar içeriyor.', type: 'verb', level: 'B1' },
    { word: 'content', turkishTranslation: 'memnun', definitionTr: 'Hoşnut', exampleSentence: 'I am content with my life.', exampleSentenceTr: 'Hayatımdan memnunum.', type: 'adjective', level: 'B1' },
    { word: 'continue', turkishTranslation: 'devam etmek', definitionTr: 'Sürdürmek', exampleSentence: 'Please continue with your work.', exampleSentenceTr: 'Lütfen işinize devam edin.', type: 'verb', level: 'A2' },
    { word: 'contribute', turkishTranslation: 'katkıda bulunmak', definitionTr: 'Yardım etmek', exampleSentence: 'Everyone should contribute to the project.', exampleSentenceTr: 'Herkes projeye katkıda bulunmalı.', type: 'verb', level: 'B1' },
    { word: 'control', turkishTranslation: 'kontrol etmek', definitionTr: 'Yönetmek', exampleSentence: 'You need to control your emotions.', exampleSentenceTr: 'Duygularını kontrol etmelisin.', type: 'verb', level: 'A2' },
    { word: 'convince', turkishTranslation: 'ikna etmek', definitionTr: 'İnandırmak', exampleSentence: 'I tried to convince him.', exampleSentenceTr: 'Onu ikna etmeye çalıştım.', type: 'verb', level: 'B1' },
    { word: 'correct', turkishTranslation: 'doğru', definitionTr: 'Hatasız', exampleSentence: 'Your answer is correct.', exampleSentenceTr: 'Cevabın doğru.', type: 'adjective', level: 'A2' },
    { word: 'create', turkishTranslation: 'yaratmak', definitionTr: 'Oluşturmak', exampleSentence: 'Artists create beautiful works.', exampleSentenceTr: 'Sanatçılar güzel eserler yaratır.', type: 'verb', level: 'A2' },
    { word: 'curious', turkishTranslation: 'meraklı', definitionTr: 'Öğrenmeye hevesli', exampleSentence: 'Children are naturally curious.', exampleSentenceTr: 'Çocuklar doğal olarak meraklıdır.', type: 'adjective', level: 'B1' },
    { word: 'current', turkishTranslation: 'güncel', definitionTr: 'Şu anki', exampleSentence: 'What is your current address?', exampleSentenceTr: 'Güncel adresiniz nedir?', type: 'adjective', level: 'B1' },
    { word: 'damage', turkishTranslation: 'hasar', definitionTr: 'Zarar', exampleSentence: 'The storm caused a lot of damage.', exampleSentenceTr: 'Fırtına çok hasar verdi.', type: 'noun', level: 'B1' },
    { word: 'deal', turkishTranslation: 'anlaşma', definitionTr: 'İş, pazarlık', exampleSentence: 'We made a deal.', exampleSentenceTr: 'Bir anlaşma yaptık.', type: 'noun', level: 'B1' },
    { word: 'decide', turkishTranslation: 'karar vermek', definitionTr: 'Seçim yapmak', exampleSentence: 'I decided to stay home.', exampleSentenceTr: 'Evde kalmaya karar verdim.', type: 'verb', level: 'A2' },
    { word: 'decrease', turkishTranslation: 'azalmak', definitionTr: 'Düşmek', exampleSentence: 'Sales decreased this month.', exampleSentenceTr: 'Satışlar bu ay azaldı.', type: 'verb', level: 'B1' },
    { word: 'define', turkishTranslation: 'tanımlamak', definitionTr: 'Açıklamak', exampleSentence: 'Can you define this word?', exampleSentenceTr: 'Bu kelimeyi tanımlayabilir misin?', type: 'verb', level: 'B1' },
    { word: 'definitely', turkishTranslation: 'kesinlikle', definitionTr: 'Şüphesiz', exampleSentence: 'I will definitely come.', exampleSentenceTr: 'Kesinlikle geleceğim.', type: 'adverb', level: 'A2' },
    { word: 'demand', turkishTranslation: 'talep', definitionTr: 'İstek', exampleSentence: 'There is high demand for this product.', exampleSentenceTr: 'Bu ürüne yüksek talep var.', type: 'noun', level: 'B1' },
    { word: 'demonstrate', turkishTranslation: 'göstermek', definitionTr: 'Kanıtlamak', exampleSentence: 'Let me demonstrate how it works.', exampleSentenceTr: 'Nasıl çalıştığını göstereyim.', type: 'verb', level: 'B1' },
    { word: 'deny', turkishTranslation: 'inkar etmek', definitionTr: 'Reddetmek', exampleSentence: 'He denied the accusations.', exampleSentenceTr: 'Suçlamaları inkar etti.', type: 'verb', level: 'B1' },
    { word: 'depend', turkishTranslation: 'bağlı olmak', definitionTr: 'Güvenmek', exampleSentence: 'It depends on the weather.', exampleSentenceTr: 'Havaya bağlı.', type: 'verb', level: 'B1' },
    { word: 'describe', turkishTranslation: 'tanımlamak', definitionTr: 'Betimlemek', exampleSentence: 'Can you describe the thief?', exampleSentenceTr: 'Hırsızı tanımlayabilir misiniz?', type: 'verb', level: 'A2' },
    { word: 'deserve', turkishTranslation: 'hak etmek', definitionTr: 'Layık olmak', exampleSentence: 'You deserve a break.', exampleSentenceTr: 'Bir molayı hak ediyorsun.', type: 'verb', level: 'B1' },
    { word: 'desire', turkishTranslation: 'arzu', definitionTr: 'Güçlü istek', exampleSentence: 'She has a strong desire to succeed.', exampleSentenceTr: 'Başarılı olma arzusu güçlü.', type: 'noun', level: 'B1' },
    { word: 'destroy', turkishTranslation: 'yok etmek', definitionTr: 'Tahrip etmek', exampleSentence: 'The fire destroyed the building.', exampleSentenceTr: 'Yangın binayı yok etti.', type: 'verb', level: 'B1' },
    { word: 'detail', turkishTranslation: 'detay', definitionTr: 'Ayrıntı', exampleSentence: 'Pay attention to every detail.', exampleSentenceTr: 'Her detaya dikkat et.', type: 'noun', level: 'B1' },
    { word: 'determine', turkishTranslation: 'belirlemek', definitionTr: 'Tespit etmek', exampleSentence: 'We need to determine the cause.', exampleSentenceTr: 'Nedeni belirlememiz gerekiyor.', type: 'verb', level: 'B1' },
    { word: 'develop', turkishTranslation: 'geliştirmek', definitionTr: 'İlerletmek', exampleSentence: 'We want to develop new skills.', exampleSentenceTr: 'Yeni beceriler geliştirmek istiyoruz.', type: 'verb', level: 'B1' },
    { word: 'differ', turkishTranslation: 'farklı olmak', definitionTr: 'Ayrılmak', exampleSentence: 'Our opinions differ.', exampleSentenceTr: 'Görüşlerimiz farklı.', type: 'verb', level: 'B1' },
    { word: 'difficult', turkishTranslation: 'zor', definitionTr: 'Güç', exampleSentence: 'This exam is very difficult.', exampleSentenceTr: 'Bu sınav çok zor.', type: 'adjective', level: 'A2' },
    { word: 'direct', turkishTranslation: 'doğrudan', definitionTr: 'Direkt', exampleSentence: 'Take the direct route.', exampleSentenceTr: 'Doğrudan yolu kullan.', type: 'adjective', level: 'B1' },
    { word: 'disappoint', turkishTranslation: 'hayal kırıklığına uğratmak', definitionTr: 'Üzmek', exampleSentence: 'I do not want to disappoint you.', exampleSentenceTr: 'Seni hayal kırıklığına uğratmak istemiyorum.', type: 'verb', level: 'B1' },
    { word: 'discover', turkishTranslation: 'keşfetmek', definitionTr: 'Bulmak', exampleSentence: 'Scientists discovered a new planet.', exampleSentenceTr: 'Bilim insanları yeni bir gezegen keşfetti.', type: 'verb', level: 'B1' },
    { word: 'discuss', turkishTranslation: 'tartışmak', definitionTr: 'Konuşmak', exampleSentence: 'Let us discuss this matter.', exampleSentenceTr: 'Bu konuyu tartışalım.', type: 'verb', level: 'B1' },
    { word: 'distance', turkishTranslation: 'mesafe', definitionTr: 'Uzaklık', exampleSentence: 'What is the distance to the airport?', exampleSentenceTr: 'Havalimanına mesafe ne kadar?', type: 'noun', level: 'A2' },
    { word: 'divide', turkishTranslation: 'bölmek', definitionTr: 'Ayırmak', exampleSentence: 'Divide the cake into equal pieces.', exampleSentenceTr: 'Pastayı eşit parçalara böl.', type: 'verb', level: 'B1' },
    { word: 'doubt', turkishTranslation: 'şüphe', definitionTr: 'Tereddüt', exampleSentence: 'I have no doubt about it.', exampleSentenceTr: 'Bu konuda hiç şüphem yok.', type: 'noun', level: 'B1' },
];
