// src/lib/wordBankAcademic.ts
// Akademik kategorisi - 100+ kelime

import { WordData } from './wordBank';

export const academicWords: WordData[] = [
    { word: 'abstract', turkishTranslation: 'özet', definitionTr: 'Makale özeti', exampleSentence: 'Read the abstract first.', exampleSentenceTr: 'Önce özeti okuyun.', type: 'noun', level: 'B2' },
    { word: 'accurate', turkishTranslation: 'doğru', definitionTr: 'Hatasız', exampleSentence: 'The data must be accurate.', exampleSentenceTr: 'Veriler doğru olmalı.', type: 'adjective', level: 'B1' },
    { word: 'acknowledge', turkishTranslation: 'kabul etmek', definitionTr: 'Onaylamak', exampleSentence: 'We acknowledge your contribution.', exampleSentenceTr: 'Katkınızı kabul ediyoruz.', type: 'verb', level: 'B2' },
    { word: 'acquire', turkishTranslation: 'edinmek', definitionTr: 'Kazanmak', exampleSentence: 'Students acquire knowledge.', exampleSentenceTr: 'Öğrenciler bilgi edinir.', type: 'verb', level: 'B2' },
    { word: 'adapt', turkishTranslation: 'uyarlamak', definitionTr: 'Uyum sağlamak', exampleSentence: 'Adapt to new situations.', exampleSentenceTr: 'Yeni durumlara uyum sağla.', type: 'verb', level: 'B1' },
    { word: 'adequate', turkishTranslation: 'yeterli', definitionTr: 'Uygun miktarda', exampleSentence: 'Is the evidence adequate?', exampleSentenceTr: 'Kanıtlar yeterli mi?', type: 'adjective', level: 'B2' },
    { word: 'advocate', turkishTranslation: 'savunmak', definitionTr: 'Desteklemek', exampleSentence: 'I advocate for education reform.', exampleSentenceTr: 'Eğitim reformunu savunuyorum.', type: 'verb', level: 'B2' },
    { word: 'allocate', turkishTranslation: 'tahsis etmek', definitionTr: 'Ayırmak', exampleSentence: 'Allocate resources wisely.', exampleSentenceTr: 'Kaynakları akıllıca tahsis edin.', type: 'verb', level: 'B2' },
    { word: 'alter', turkishTranslation: 'değiştirmek', definitionTr: 'Farklılaştırmak', exampleSentence: 'Do not alter the data.', exampleSentenceTr: 'Verileri değiştirmeyin.', type: 'verb', level: 'B2' },
    { word: 'ambiguous', turkishTranslation: 'belirsiz', definitionTr: 'Muğlak', exampleSentence: 'The results are ambiguous.', exampleSentenceTr: 'Sonuçlar belirsiz.', type: 'adjective', level: 'B2' },
    { word: 'analyze', turkishTranslation: 'analiz etmek', definitionTr: 'İncelemek', exampleSentence: 'Analyze the data carefully.', exampleSentenceTr: 'Verileri dikkatle analiz edin.', type: 'verb', level: 'B1' },
    { word: 'apparent', turkishTranslation: 'açık', definitionTr: 'Görünür', exampleSentence: 'The answer is apparent.', exampleSentenceTr: 'Cevap açık.', type: 'adjective', level: 'B2' },
    { word: 'appendix', turkishTranslation: 'ek', definitionTr: 'Eklenti', exampleSentence: 'See the appendix for details.', exampleSentenceTr: 'Detaylar için eke bakın.', type: 'noun', level: 'B2' },
    { word: 'approach', turkishTranslation: 'yaklaşım', definitionTr: 'Yöntem', exampleSentence: 'Use a scientific approach.', exampleSentenceTr: 'Bilimsel yaklaşım kullanın.', type: 'noun', level: 'B1' },
    { word: 'arbitrary', turkishTranslation: 'keyfi', definitionTr: 'Rastgele', exampleSentence: 'This is an arbitrary decision.', exampleSentenceTr: 'Bu keyfi bir karar.', type: 'adjective', level: 'C1' },
    { word: 'aspect', turkishTranslation: 'yön', definitionTr: 'Boyut', exampleSentence: 'Consider every aspect.', exampleSentenceTr: 'Her yönü düşünün.', type: 'noun', level: 'B1' },
    { word: 'assess', turkishTranslation: 'değerlendirmek', definitionTr: 'Ölçmek', exampleSentence: 'Assess your progress regularly.', exampleSentenceTr: 'İlerlemenizi düzenli değerlendirin.', type: 'verb', level: 'B1' },
    { word: 'assume', turkishTranslation: 'varsaymak', definitionTr: 'Kabul etmek', exampleSentence: 'Let us assume this is true.', exampleSentenceTr: 'Bunun doğru olduğunu varsayalım.', type: 'verb', level: 'B1' },
    { word: 'attribute', turkishTranslation: 'atfetmek', definitionTr: 'Bağlamak', exampleSentence: 'We attribute success to hard work.', exampleSentenceTr: 'Başarıyı çalışkanlığa atfediyoruz.', type: 'verb', level: 'B2' },
    { word: 'authority', turkishTranslation: 'otorite', definitionTr: 'Yetki', exampleSentence: 'He is an authority on the subject.', exampleSentenceTr: 'Konuda otorite biri.', type: 'noun', level: 'B1' },
    { word: 'bias', turkishTranslation: 'önyargı', definitionTr: 'Ön yargı', exampleSentence: 'Avoid bias in your research.', exampleSentenceTr: 'Araştırmanızda önyargıdan kaçının.', type: 'noun', level: 'B2' },
    { word: 'bibliography', turkishTranslation: 'kaynakça', definitionTr: 'Kaynak listesi', exampleSentence: 'Check the bibliography.', exampleSentenceTr: 'Kaynakçayı kontrol edin.', type: 'noun', level: 'B2' },
    { word: 'capable', turkishTranslation: 'yetenekli', definitionTr: 'Muktedir', exampleSentence: 'Students are capable of learning.', exampleSentenceTr: 'Öğrenciler öğrenmeye yetenekli.', type: 'adjective', level: 'B1' },
    { word: 'chapter', turkishTranslation: 'bölüm', definitionTr: 'Kitap bölümü', exampleSentence: 'Read chapter 3 for homework.', exampleSentenceTr: 'Ödev için 3. bölümü okuyun.', type: 'noun', level: 'A2' },
    { word: 'cite', turkishTranslation: 'alıntı yapmak', definitionTr: 'Kaynak göstermek', exampleSentence: 'Cite your sources properly.', exampleSentenceTr: 'Kaynaklarınızı düzgün gösterin.', type: 'verb', level: 'B2' },
    { word: 'clarify', turkishTranslation: 'açıklığa kavuşturmak', definitionTr: 'Netleştirmek', exampleSentence: 'Please clarify your statement.', exampleSentenceTr: 'Lütfen ifadenizi açıklayın.', type: 'verb', level: 'B1' },
    { word: 'classic', turkishTranslation: 'klasik', definitionTr: 'Geleneksel', exampleSentence: 'This is a classic example.', exampleSentenceTr: 'Bu klasik bir örnek.', type: 'adjective', level: 'B1' },
    { word: 'clause', turkishTranslation: 'cümle', definitionTr: 'Dilbilgisi birimi', exampleSentence: 'Identify the main clause.', exampleSentenceTr: 'Ana cümleyi belirleyin.', type: 'noun', level: 'B2' },
    { word: 'coherent', turkishTranslation: 'tutarlı', definitionTr: 'Mantıklı', exampleSentence: 'Write a coherent argument.', exampleSentenceTr: 'Tutarlı bir argüman yazın.', type: 'adjective', level: 'B2' },
    { word: 'collapse', turkishTranslation: 'çökmek', definitionTr: 'Yıkılmak', exampleSentence: 'The theory may collapse.', exampleSentenceTr: 'Teori çökebilir.', type: 'verb', level: 'B2' },
    { word: 'component', turkishTranslation: 'bileşen', definitionTr: 'Parça', exampleSentence: 'List the main components.', exampleSentenceTr: 'Ana bileşenleri sıralayın.', type: 'noun', level: 'B1' },
    { word: 'comprehensive', turkishTranslation: 'kapsamlı', definitionTr: 'Geniş', exampleSentence: 'This is a comprehensive study.', exampleSentenceTr: 'Bu kapsamlı bir çalışma.', type: 'adjective', level: 'B2' },
    { word: 'concept', turkishTranslation: 'kavram', definitionTr: 'Fikir', exampleSentence: 'Explain the main concept.', exampleSentenceTr: 'Ana kavramı açıklayın.', type: 'noun', level: 'B1' },
    { word: 'conclude', turkishTranslation: 'sonuç çıkarmak', definitionTr: 'Bitirmek', exampleSentence: 'We conclude that it works.', exampleSentenceTr: 'İşe yaradığı sonucuna varıyoruz.', type: 'verb', level: 'B1' },
    { word: 'conduct', turkishTranslation: 'yürütmek', definitionTr: 'Gerçekleştirmek', exampleSentence: 'Conduct an experiment.', exampleSentenceTr: 'Bir deney yürütün.', type: 'verb', level: 'B1' },
    { word: 'confine', turkishTranslation: 'sınırlamak', definitionTr: 'Kısıtlamak', exampleSentence: 'Confine your answer to one page.', exampleSentenceTr: 'Cevabınızı bir sayfayla sınırlayın.', type: 'verb', level: 'B2' },
    { word: 'consequence', turkishTranslation: 'sonuç', definitionTr: 'Netice', exampleSentence: 'Consider the consequences.', exampleSentenceTr: 'Sonuçları düşünün.', type: 'noun', level: 'B1' },
    { word: 'consistent', turkishTranslation: 'tutarlı', definitionTr: 'Değişmeyen', exampleSentence: 'Be consistent in your work.', exampleSentenceTr: 'Çalışmanızda tutarlı olun.', type: 'adjective', level: 'B1' },
    { word: 'constant', turkishTranslation: 'sabit', definitionTr: 'Değişmeyen', exampleSentence: 'Keep the temperature constant.', exampleSentenceTr: 'Sıcaklığı sabit tutun.', type: 'adjective', level: 'B1' },
    { word: 'constitute', turkishTranslation: 'oluşturmak', definitionTr: 'Meydana getirmek', exampleSentence: 'These elements constitute the whole.', exampleSentenceTr: 'Bu öğeler bütünü oluşturur.', type: 'verb', level: 'B2' },
    { word: 'constraint', turkishTranslation: 'kısıtlama', definitionTr: 'Sınırlama', exampleSentence: 'Work within the constraints.', exampleSentenceTr: 'Kısıtlamalar dahilinde çalışın.', type: 'noun', level: 'B2' },
    { word: 'construct', turkishTranslation: 'inşa etmek', definitionTr: 'Yapılandırmak', exampleSentence: 'Construct a valid argument.', exampleSentenceTr: 'Geçerli bir argüman oluşturun.', type: 'verb', level: 'B1' },
    { word: 'context', turkishTranslation: 'bağlam', definitionTr: 'Çevre', exampleSentence: 'Consider the historical context.', exampleSentenceTr: 'Tarihsel bağlamı düşünün.', type: 'noun', level: 'B1' },
    { word: 'contradict', turkishTranslation: 'çelişmek', definitionTr: 'Ters düşmek', exampleSentence: 'The findings contradict each other.', exampleSentenceTr: 'Bulgular birbiriyle çelişiyor.', type: 'verb', level: 'B2' },
    { word: 'contrast', turkishTranslation: 'karşıtlık', definitionTr: 'Farklılık', exampleSentence: 'Note the contrast between them.', exampleSentenceTr: 'Aralarındaki karşıtlığa dikkat edin.', type: 'noun', level: 'B1' },
    { word: 'contribute', turkishTranslation: 'katkıda bulunmak', definitionTr: 'Yardım etmek', exampleSentence: 'How did this contribute to the result?', exampleSentenceTr: 'Bu sonuca nasıl katkıda bulundu?', type: 'verb', level: 'B1' },
    { word: 'controversy', turkishTranslation: 'tartışma', definitionTr: 'Anlaşmazlık', exampleSentence: 'This caused much controversy.', exampleSentenceTr: 'Bu çok tartışmaya neden oldu.', type: 'noun', level: 'B2' },
    { word: 'convince', turkishTranslation: 'ikna etmek', definitionTr: 'İnandırmak', exampleSentence: 'Convince me with evidence.', exampleSentenceTr: 'Beni kanıtlarla ikna et.', type: 'verb', level: 'B1' },
    { word: 'core', turkishTranslation: 'çekirdek', definitionTr: 'Merkez', exampleSentence: 'Focus on the core issues.', exampleSentenceTr: 'Temel konulara odaklanın.', type: 'noun', level: 'B1' },
    { word: 'correspond', turkishTranslation: 'karşılık gelmek', definitionTr: 'Eşleşmek', exampleSentence: 'The results correspond to the theory.', exampleSentenceTr: 'Sonuçlar teoriye karşılık geliyor.', type: 'verb', level: 'B2' },
    { word: 'criteria', turkishTranslation: 'kriterler', definitionTr: 'Ölçütler', exampleSentence: 'Meet all the criteria.', exampleSentenceTr: 'Tüm kriterleri karşılayın.', type: 'noun', level: 'B1' },
    { word: 'crucial', turkishTranslation: 'çok önemli', definitionTr: 'Kritik', exampleSentence: 'This is a crucial point.', exampleSentenceTr: 'Bu çok önemli bir nokta.', type: 'adjective', level: 'B2' },
    { word: 'data', turkishTranslation: 'veri', definitionTr: 'Bilgi', exampleSentence: 'Collect the data carefully.', exampleSentenceTr: 'Verileri dikkatle toplayın.', type: 'noun', level: 'A2' },
    { word: 'debate', turkishTranslation: 'tartışma', definitionTr: 'Münazara', exampleSentence: 'There is much debate on this topic.', exampleSentenceTr: 'Bu konuda çok tartışma var.', type: 'noun', level: 'B1' },
    { word: 'decline', turkishTranslation: 'düşüş', definitionTr: 'Azalma', exampleSentence: 'There was a decline in quality.', exampleSentenceTr: 'Kalitede düşüş oldu.', type: 'noun', level: 'B1' },
    { word: 'deduce', turkishTranslation: 'sonuç çıkarmak', definitionTr: 'Anlamak', exampleSentence: 'What can we deduce from this?', exampleSentenceTr: 'Bundan ne sonuç çıkarabiliriz?', type: 'verb', level: 'B2' },
    { word: 'define', turkishTranslation: 'tanımlamak', definitionTr: 'Açıklamak', exampleSentence: 'Define the key terms.', exampleSentenceTr: 'Anahtar terimleri tanımlayın.', type: 'verb', level: 'B1' },
    { word: 'demonstrate', turkishTranslation: 'göstermek', definitionTr: 'Kanıtlamak', exampleSentence: 'The study demonstrates this.', exampleSentenceTr: 'Çalışma bunu gösteriyor.', type: 'verb', level: 'B1' },
    { word: 'denote', turkishTranslation: 'belirtmek', definitionTr: 'İfade etmek', exampleSentence: 'X denotes the variable.', exampleSentenceTr: 'X değişkeni belirtir.', type: 'verb', level: 'C1' },
    { word: 'derive', turkishTranslation: 'türetmek', definitionTr: 'Elde etmek', exampleSentence: 'The word derives from Latin.', exampleSentenceTr: 'Kelime Latinceden türemiş.', type: 'verb', level: 'B2' },
    { word: 'design', turkishTranslation: 'tasarım', definitionTr: 'Plan', exampleSentence: 'Explain the research design.', exampleSentenceTr: 'Araştırma tasarımını açıklayın.', type: 'noun', level: 'B1' },
    { word: 'detect', turkishTranslation: 'tespit etmek', definitionTr: 'Bulmak', exampleSentence: 'We detected an error.', exampleSentenceTr: 'Bir hata tespit ettik.', type: 'verb', level: 'B1' },
    { word: 'dimension', turkishTranslation: 'boyut', definitionTr: 'Ölçü', exampleSentence: 'Consider all dimensions.', exampleSentenceTr: 'Tüm boyutları düşünün.', type: 'noun', level: 'B1' },
    { word: 'distinct', turkishTranslation: 'farklı', definitionTr: 'Ayrı', exampleSentence: 'These are distinct categories.', exampleSentenceTr: 'Bunlar farklı kategoriler.', type: 'adjective', level: 'B2' },
    { word: 'domain', turkishTranslation: 'alan', definitionTr: 'Etki alanı', exampleSentence: 'This is outside my domain.', exampleSentenceTr: 'Bu benim alanım dışında.', type: 'noun', level: 'B2' },
    { word: 'draft', turkishTranslation: 'taslak', definitionTr: 'İlk versiyon', exampleSentence: 'Submit your first draft.', exampleSentenceTr: 'İlk taslağınızı gönderin.', type: 'noun', level: 'B1' },
    { word: 'dynamic', turkishTranslation: 'dinamik', definitionTr: 'Değişken', exampleSentence: 'Language is dynamic.', exampleSentenceTr: 'Dil dinamiktir.', type: 'adjective', level: 'B2' },
    { word: 'element', turkishTranslation: 'öğe', definitionTr: 'Parça', exampleSentence: 'Identify the key elements.', exampleSentenceTr: 'Anahtar öğeleri belirleyin.', type: 'noun', level: 'B1' },
    { word: 'eliminate', turkishTranslation: 'elemek', definitionTr: 'Çıkarmak', exampleSentence: 'Eliminate unnecessary words.', exampleSentenceTr: 'Gereksiz kelimeleri eleyin.', type: 'verb', level: 'B1' },
    { word: 'emerge', turkishTranslation: 'ortaya çıkmak', definitionTr: 'Belirmek', exampleSentence: 'New theories emerge.', exampleSentenceTr: 'Yeni teoriler ortaya çıkıyor.', type: 'verb', level: 'B2' },
    { word: 'emphasis', turkishTranslation: 'vurgu', definitionTr: 'Önem', exampleSentence: 'Put more emphasis on this.', exampleSentenceTr: 'Buna daha fazla vurgu yapın.', type: 'noun', level: 'B1' },
    { word: 'empirical', turkishTranslation: 'deneysel', definitionTr: 'Gözleme dayalı', exampleSentence: 'We need empirical evidence.', exampleSentenceTr: 'Deneysel kanıtlara ihtiyacımız var.', type: 'adjective', level: 'C1' },
    { word: 'enable', turkishTranslation: 'imkan vermek', definitionTr: 'Sağlamak', exampleSentence: 'This will enable further research.', exampleSentenceTr: 'Bu daha fazla araştırmaya imkan verecek.', type: 'verb', level: 'B1' },
    { word: 'encounter', turkishTranslation: 'karşılaşmak', definitionTr: 'Rastlamak', exampleSentence: 'We encountered difficulties.', exampleSentenceTr: 'Zorluklarla karşılaştık.', type: 'verb', level: 'B2' },
    { word: 'ensure', turkishTranslation: 'sağlamak', definitionTr: 'Garantilemek', exampleSentence: 'Ensure accuracy in your work.', exampleSentenceTr: 'Çalışmanızda doğruluğu sağlayın.', type: 'verb', level: 'B1' },
    { word: 'entity', turkishTranslation: 'varlık', definitionTr: 'Nesne', exampleSentence: 'Consider it as a separate entity.', exampleSentenceTr: 'Ayrı bir varlık olarak düşünün.', type: 'noun', level: 'C1' },
    { word: 'environment', turkishTranslation: 'çevre', definitionTr: 'Ortam', exampleSentence: 'Create a learning environment.', exampleSentenceTr: 'Öğrenme ortamı oluşturun.', type: 'noun', level: 'A2' },
    { word: 'equivalent', turkishTranslation: 'eşdeğer', definitionTr: 'Eş', exampleSentence: 'Find the equivalent term.', exampleSentenceTr: 'Eşdeğer terimi bulun.', type: 'adjective', level: 'B2' },
    { word: 'error', turkishTranslation: 'hata', definitionTr: 'Yanlışlık', exampleSentence: 'Correct the errors.', exampleSentenceTr: 'Hataları düzeltin.', type: 'noun', level: 'A2' },
    { word: 'establish', turkishTranslation: 'kurmak', definitionTr: 'Oluşturmak', exampleSentence: 'Establish clear guidelines.', exampleSentenceTr: 'Net kurallar oluşturun.', type: 'verb', level: 'B1' },
    { word: 'evaluate', turkishTranslation: 'değerlendirmek', definitionTr: 'Ölçmek', exampleSentence: 'Evaluate the results.', exampleSentenceTr: 'Sonuçları değerlendirin.', type: 'verb', level: 'B1' },
    { word: 'evidence', turkishTranslation: 'kanıt', definitionTr: 'Delil', exampleSentence: 'Provide supporting evidence.', exampleSentenceTr: 'Destekleyici kanıt sağlayın.', type: 'noun', level: 'B1' },
    { word: 'evolve', turkishTranslation: 'evrim geçirmek', definitionTr: 'Gelişmek', exampleSentence: 'Languages evolve over time.', exampleSentenceTr: 'Diller zamanla evrim geçirir.', type: 'verb', level: 'B2' },
    { word: 'examine', turkishTranslation: 'incelemek', definitionTr: 'Araştırmak', exampleSentence: 'Examine the data closely.', exampleSentenceTr: 'Verileri yakından inceleyin.', type: 'verb', level: 'B1' },
    { word: 'exceed', turkishTranslation: 'aşmak', definitionTr: 'Geçmek', exampleSentence: 'Do not exceed the limit.', exampleSentenceTr: 'Limiti aşmayın.', type: 'verb', level: 'B2' },
    { word: 'exclude', turkishTranslation: 'hariç tutmak', definitionTr: 'Dahil etmemek', exampleSentence: 'We must exclude these cases.', exampleSentenceTr: 'Bu vakaları hariç tutmalıyız.', type: 'verb', level: 'B2' },
    { word: 'expand', turkishTranslation: 'genişletmek', definitionTr: 'Büyütmek', exampleSentence: 'Expand on this idea.', exampleSentenceTr: 'Bu fikri genişletin.', type: 'verb', level: 'B1' },
    { word: 'expert', turkishTranslation: 'uzman', definitionTr: 'Bilirkişi', exampleSentence: 'Consult an expert.', exampleSentenceTr: 'Bir uzmana danışın.', type: 'noun', level: 'A2' },
    { word: 'explicit', turkishTranslation: 'açık', definitionTr: 'Net', exampleSentence: 'Be explicit in your writing.', exampleSentenceTr: 'Yazınızda açık olun.', type: 'adjective', level: 'B2' },
    { word: 'exploit', turkishTranslation: 'kullanmak', definitionTr: 'Yararlanmak', exampleSentence: 'Exploit the opportunity.', exampleSentenceTr: 'Fırsatı değerlendirin.', type: 'verb', level: 'B2' },
    { word: 'expose', turkishTranslation: 'maruz bırakmak', definitionTr: 'Açığa çıkarmak', exampleSentence: 'Expose the problems.', exampleSentenceTr: 'Sorunları ortaya çıkarın.', type: 'verb', level: 'B2' },
    { word: 'extract', turkishTranslation: 'çıkarmak', definitionTr: 'Elde etmek', exampleSentence: 'Extract the key information.', exampleSentenceTr: 'Anahtar bilgiyi çıkarın.', type: 'verb', level: 'B2' },
    { word: 'factor', turkishTranslation: 'faktör', definitionTr: 'Etken', exampleSentence: 'Consider all factors.', exampleSentenceTr: 'Tüm faktörleri düşünün.', type: 'noun', level: 'B1' },
    { word: 'feature', turkishTranslation: 'özellik', definitionTr: 'Nitelik', exampleSentence: 'Describe the main features.', exampleSentenceTr: 'Ana özellikleri tanımlayın.', type: 'noun', level: 'B1' },
    { word: 'final', turkishTranslation: 'final', definitionTr: 'Son', exampleSentence: 'Submit your final draft.', exampleSentenceTr: 'Son taslağınızı gönderin.', type: 'adjective', level: 'A2' },
    { word: 'focus', turkishTranslation: 'odak', definitionTr: 'Merkez', exampleSentence: 'The main focus is on results.', exampleSentenceTr: 'Ana odak sonuçlar üzerinde.', type: 'noun', level: 'B1' },
    { word: 'formula', turkishTranslation: 'formül', definitionTr: 'Hesap yöntemi', exampleSentence: 'Apply the formula correctly.', exampleSentenceTr: 'Formülü doğru uygulayın.', type: 'noun', level: 'B1' },
    { word: 'framework', turkishTranslation: 'çerçeve', definitionTr: 'Yapı', exampleSentence: 'Use a theoretical framework.', exampleSentenceTr: 'Teorik çerçeve kullanın.', type: 'noun', level: 'B2' },
    { word: 'function', turkishTranslation: 'işlev', definitionTr: 'Görev', exampleSentence: 'Explain the function of this.', exampleSentenceTr: 'Bunun işlevini açıklayın.', type: 'noun', level: 'B1' },
];
