// src/lib/wordBankTravel.ts
// Seyahat kategorisi - 100+ kelime

import { WordData } from './wordBank';

export const travelWords: WordData[] = [
    { word: 'abroad', turkishTranslation: 'yurt dışında', definitionTr: 'Başka ülkede', exampleSentence: 'I want to study abroad.', exampleSentenceTr: 'Yurt dışında okumak istiyorum.', type: 'adverb', level: 'A2' },
    { word: 'accommodation', turkishTranslation: 'konaklama', definitionTr: 'Kalacak yer', exampleSentence: 'Have you booked your accommodation?', exampleSentenceTr: 'Konaklama rezervasyonu yaptınız mı?', type: 'noun', level: 'B1' },
    { word: 'adventure', turkishTranslation: 'macera', definitionTr: 'Heyecanlı deneyim', exampleSentence: 'Every trip is an adventure.', exampleSentenceTr: 'Her gezi bir maceradır.', type: 'noun', level: 'A2' },
    { word: 'airline', turkishTranslation: 'havayolu', definitionTr: 'Uçak şirketi', exampleSentence: 'Which airline are you flying with?', exampleSentenceTr: 'Hangi havayoluyla uçuyorsunuz?', type: 'noun', level: 'A2' },
    { word: 'airport', turkishTranslation: 'havalimanı', definitionTr: 'Uçak terminali', exampleSentence: 'The airport is 20 km away.', exampleSentenceTr: 'Havalimanı 20 km uzaklıkta.', type: 'noun', level: 'A1' },
    { word: 'aisle', turkishTranslation: 'koridor', definitionTr: 'Geçit', exampleSentence: 'I prefer an aisle seat.', exampleSentenceTr: 'Koridor tarafı koltuğu tercih ederim.', type: 'noun', level: 'B1' },
    { word: 'arrival', turkishTranslation: 'varış', definitionTr: 'Gelme', exampleSentence: 'Check the arrival time.', exampleSentenceTr: 'Varış saatini kontrol edin.', type: 'noun', level: 'A2' },
    { word: 'attraction', turkishTranslation: 'turistik yer', definitionTr: 'Görülecek yer', exampleSentence: 'What are the main attractions?', exampleSentenceTr: 'Başlıca turistik yerler nelerdir?', type: 'noun', level: 'B1' },
    { word: 'baggage', turkishTranslation: 'bagaj', definitionTr: 'Yolcu çantaları', exampleSentence: 'Where is baggage claim?', exampleSentenceTr: 'Bagaj alım yeri nerede?', type: 'noun', level: 'A2' },
    { word: 'beach', turkishTranslation: 'plaj', definitionTr: 'Kumsal', exampleSentence: 'The beach is beautiful here.', exampleSentenceTr: 'Burada plaj çok güzel.', type: 'noun', level: 'A1' },
    { word: 'boarding', turkishTranslation: 'biniş', definitionTr: 'Taşıta binme', exampleSentence: 'Boarding starts in 30 minutes.', exampleSentenceTr: 'Biniş 30 dakika sonra başlıyor.', type: 'noun', level: 'A2' },
    { word: 'book', turkishTranslation: 'rezervasyon yapmak', definitionTr: 'Yer ayırtmak', exampleSentence: 'I need to book a hotel.', exampleSentenceTr: 'Otel rezervasyonu yapmam lazım.', type: 'verb', level: 'A2' },
    { word: 'border', turkishTranslation: 'sınır', definitionTr: 'Ülke sınırı', exampleSentence: 'We crossed the border by bus.', exampleSentenceTr: 'Sınırı otobüsle geçtik.', type: 'noun', level: 'B1' },
    { word: 'brochure', turkishTranslation: 'broşür', definitionTr: 'Tanıtım kitapçığı', exampleSentence: 'Take a travel brochure.', exampleSentenceTr: 'Bir seyahat broşürü alın.', type: 'noun', level: 'B1' },
    { word: 'cabin', turkishTranslation: 'kabin', definitionTr: 'Uçak bölümü', exampleSentence: 'The cabin crew was helpful.', exampleSentenceTr: 'Kabin ekibi yardımcı oldu.', type: 'noun', level: 'B1' },
    { word: 'cancel', turkishTranslation: 'iptal etmek', definitionTr: 'Vazgeçmek', exampleSentence: 'I need to cancel my reservation.', exampleSentenceTr: 'Rezervasyonumu iptal etmem lazım.', type: 'verb', level: 'A2' },
    { word: 'carry-on', turkishTranslation: 'el bagajı', definitionTr: 'Yanına alınan çanta', exampleSentence: 'Your carry-on is too big.', exampleSentenceTr: 'El bagajınız çok büyük.', type: 'noun', level: 'B1' },
    { word: 'check-in', turkishTranslation: 'giriş yapmak', definitionTr: 'Kayıt yaptırmak', exampleSentence: 'Check-in starts at 2 PM.', exampleSentenceTr: 'Giriş saat 14:00\'te başlıyor.', type: 'noun', level: 'A2' },
    { word: 'check-out', turkishTranslation: 'çıkış yapmak', definitionTr: 'Otelden ayrılmak', exampleSentence: 'Check-out is at 11 AM.', exampleSentenceTr: 'Çıkış saat 11:00\'de.', type: 'noun', level: 'A2' },
    { word: 'connection', turkishTranslation: 'aktarma', definitionTr: 'Bağlantı uçuşu', exampleSentence: 'I missed my connection.', exampleSentenceTr: 'Aktarma uçuşumu kaçırdım.', type: 'noun', level: 'B1' },
    { word: 'cruise', turkishTranslation: 'kruvaziyer', definitionTr: 'Gemi turu', exampleSentence: 'We went on a Mediterranean cruise.', exampleSentenceTr: 'Akdeniz kruvaziyer turuna gittik.', type: 'noun', level: 'B1' },
    { word: 'culture', turkishTranslation: 'kültür', definitionTr: 'Yaşam biçimi', exampleSentence: 'I love learning about new cultures.', exampleSentenceTr: 'Yeni kültürler öğrenmeyi seviyorum.', type: 'noun', level: 'A2' },
    { word: 'currency', turkishTranslation: 'para birimi', definitionTr: 'Döviz', exampleSentence: 'What currency do they use?', exampleSentenceTr: 'Hangi para birimini kullanıyorlar?', type: 'noun', level: 'B1' },
    { word: 'customs', turkishTranslation: 'gümrük', definitionTr: 'Sınır kontrolü', exampleSentence: 'We went through customs quickly.', exampleSentenceTr: 'Gümrükten hızlıca geçtik.', type: 'noun', level: 'B1' },
    { word: 'delay', turkishTranslation: 'gecikme', definitionTr: 'Bekleme', exampleSentence: 'There was a two-hour delay.', exampleSentenceTr: 'İki saatlik gecikme oldu.', type: 'noun', level: 'A2' },
    { word: 'departure', turkishTranslation: 'kalkış', definitionTr: 'Ayrılış', exampleSentence: 'Departure is at 8 AM.', exampleSentenceTr: 'Kalkış saat 08:00\'de.', type: 'noun', level: 'A2' },
    { word: 'destination', turkishTranslation: 'varış noktası', definitionTr: 'Gidilecek yer', exampleSentence: 'What is your destination?', exampleSentenceTr: 'Varış noktanız neresi?', type: 'noun', level: 'A2' },
    { word: 'directions', turkishTranslation: 'yol tarifi', definitionTr: 'Yön bilgisi', exampleSentence: 'Can you give me directions?', exampleSentenceTr: 'Yol tarifi verebilir misiniz?', type: 'noun', level: 'A2' },
    { word: 'domestic', turkishTranslation: 'yurt içi', definitionTr: 'Ülke içi', exampleSentence: 'This is a domestic flight.', exampleSentenceTr: 'Bu yurt içi uçuşu.', type: 'adjective', level: 'B1' },
    { word: 'embassy', turkishTranslation: 'büyükelçilik', definitionTr: 'Diplomatik temsil', exampleSentence: 'Contact the embassy for help.', exampleSentenceTr: 'Yardım için büyükelçiliğe başvurun.', type: 'noun', level: 'B1' },
    { word: 'exchange', turkishTranslation: 'döviz kuru', definitionTr: 'Para değişimi', exampleSentence: 'What is the exchange rate?', exampleSentenceTr: 'Döviz kuru nedir?', type: 'noun', level: 'B1' },
    { word: 'excursion', turkishTranslation: 'gezi', definitionTr: 'Kısa tur', exampleSentence: 'We booked a day excursion.', exampleSentenceTr: 'Günlük gezi rezervasyonu yaptık.', type: 'noun', level: 'B1' },
    { word: 'explore', turkishTranslation: 'keşfetmek', definitionTr: 'Araştırmak', exampleSentence: 'We explored the old city.', exampleSentenceTr: 'Eski şehri keşfettik.', type: 'verb', level: 'A2' },
    { word: 'fare', turkishTranslation: 'ücret', definitionTr: 'Bilet fiyatı', exampleSentence: 'The bus fare is very cheap.', exampleSentenceTr: 'Otobüs ücreti çok ucuz.', type: 'noun', level: 'B1' },
    { word: 'ferry', turkishTranslation: 'feribot', definitionTr: 'Araba taşıyan gemi', exampleSentence: 'Take the ferry to the island.', exampleSentenceTr: 'Adaya feribotla gidin.', type: 'noun', level: 'B1' },
    { word: 'flight', turkishTranslation: 'uçuş', definitionTr: 'Hava yolculuğu', exampleSentence: 'My flight is delayed.', exampleSentenceTr: 'Uçuşum gecikti.', type: 'noun', level: 'A1' },
    { word: 'foreign', turkishTranslation: 'yabancı', definitionTr: 'Başka ülkeden', exampleSentence: 'I love foreign food.', exampleSentenceTr: 'Yabancı yemekleri seviyorum.', type: 'adjective', level: 'A2' },
    { word: 'gate', turkishTranslation: 'kapı', definitionTr: 'Biniş kapısı', exampleSentence: 'Boarding at gate 15.', exampleSentenceTr: '15 numaralı kapıda biniş.', type: 'noun', level: 'A2' },
    { word: 'guide', turkishTranslation: 'rehber', definitionTr: 'Tur rehberi', exampleSentence: 'The tour guide was excellent.', exampleSentenceTr: 'Tur rehberi mükemmeldi.', type: 'noun', level: 'A2' },
    { word: 'guidebook', turkishTranslation: 'gezi rehberi', definitionTr: 'Seyahat kitabı', exampleSentence: 'I bought a guidebook.', exampleSentenceTr: 'Bir gezi rehberi satın aldım.', type: 'noun', level: 'B1' },
    { word: 'harbor', turkishTranslation: 'liman', definitionTr: 'Gemi durağı', exampleSentence: 'The ship left the harbor.', exampleSentenceTr: 'Gemi limandan ayrıldı.', type: 'noun', level: 'B1' },
    { word: 'heritage', turkishTranslation: 'miras', definitionTr: 'Kültürel miras', exampleSentence: 'This is a heritage site.', exampleSentenceTr: 'Burası bir miras alanı.', type: 'noun', level: 'B2' },
    { word: 'hike', turkishTranslation: 'yürüyüş yapmak', definitionTr: 'Doğa yürüyüşü', exampleSentence: 'We went for a long hike.', exampleSentenceTr: 'Uzun bir yürüyüşe çıktık.', type: 'verb', level: 'B1' },
    { word: 'hostel', turkishTranslation: 'hostel', definitionTr: 'Ucuz konaklama', exampleSentence: 'We stayed at a hostel.', exampleSentenceTr: 'Bir hostelde kaldık.', type: 'noun', level: 'B1' },
    { word: 'hotel', turkishTranslation: 'otel', definitionTr: 'Konaklama yeri', exampleSentence: 'The hotel has a swimming pool.', exampleSentenceTr: 'Otelin havuzu var.', type: 'noun', level: 'A1' },
    { word: 'immigration', turkishTranslation: 'göç idaresi', definitionTr: 'Pasaport kontrolü', exampleSentence: 'Immigration was very quick.', exampleSentenceTr: 'Pasaport kontrolü çok hızlıydı.', type: 'noun', level: 'B1' },
    { word: 'international', turkishTranslation: 'uluslararası', definitionTr: 'Ülkeler arası', exampleSentence: 'This is an international flight.', exampleSentenceTr: 'Bu uluslararası uçuş.', type: 'adjective', level: 'A2' },
    { word: 'itinerary', turkishTranslation: 'güzergah', definitionTr: 'Seyahat planı', exampleSentence: 'Send me the itinerary.', exampleSentenceTr: 'Bana güzergahı gönder.', type: 'noun', level: 'B2' },
    { word: 'journey', turkishTranslation: 'yolculuk', definitionTr: 'Seyahat', exampleSentence: 'The journey takes 5 hours.', exampleSentenceTr: 'Yolculuk 5 saat sürüyor.', type: 'noun', level: 'A2' },
    { word: 'landmark', turkishTranslation: 'simge yapı', definitionTr: 'Önemli yapı', exampleSentence: 'The Eiffel Tower is a famous landmark.', exampleSentenceTr: 'Eyfel Kulesi ünlü bir simge yapı.', type: 'noun', level: 'B1' },
    { word: 'language', turkishTranslation: 'dil', definitionTr: 'Konuşma dili', exampleSentence: 'What language do they speak?', exampleSentenceTr: 'Hangi dili konuşuyorlar?', type: 'noun', level: 'A1' },
    { word: 'local', turkishTranslation: 'yerel', definitionTr: 'Bölgeye ait', exampleSentence: 'Try the local food.', exampleSentenceTr: 'Yerel yemekleri deneyin.', type: 'adjective', level: 'A2' },
    { word: 'location', turkishTranslation: 'konum', definitionTr: 'Yer', exampleSentence: 'The hotel has a great location.', exampleSentenceTr: 'Otelin konumu harika.', type: 'noun', level: 'A2' },
    { word: 'lost', turkishTranslation: 'kayıp', definitionTr: 'Kaybedilmiş', exampleSentence: 'I am lost. Can you help?', exampleSentenceTr: 'Kayboldum. Yardım edebilir misiniz?', type: 'adjective', level: 'A1' },
    { word: 'luggage', turkishTranslation: 'bagaj', definitionTr: 'Valiz', exampleSentence: 'My luggage is missing.', exampleSentenceTr: 'Bagajım kayıp.', type: 'noun', level: 'A2' },
    { word: 'map', turkishTranslation: 'harita', definitionTr: 'Yol haritası', exampleSentence: 'Do you have a city map?', exampleSentenceTr: 'Şehir haritanız var mı?', type: 'noun', level: 'A1' },
    { word: 'monument', turkishTranslation: 'anıt', definitionTr: 'Tarihi yapı', exampleSentence: 'We visited the monument.', exampleSentenceTr: 'Anıtı ziyaret ettik.', type: 'noun', level: 'B1' },
    { word: 'museum', turkishTranslation: 'müze', definitionTr: 'Sergi yeri', exampleSentence: 'The museum is closed today.', exampleSentenceTr: 'Müze bugün kapalı.', type: 'noun', level: 'A1' },
    { word: 'nature', turkishTranslation: 'doğa', definitionTr: 'Tabiat', exampleSentence: 'I love being in nature.', exampleSentenceTr: 'Doğada olmayı seviyorum.', type: 'noun', level: 'A2' },
    { word: 'overnight', turkishTranslation: 'gecelik', definitionTr: 'Bir gece', exampleSentence: 'It is an overnight train.', exampleSentenceTr: 'Gecelik tren.', type: 'adjective', level: 'B1' },
    { word: 'pack', turkishTranslation: 'bavul hazırlamak', definitionTr: 'Çanta toplamak', exampleSentence: 'Have you packed yet?', exampleSentenceTr: 'Bavulunu hazırladın mı?', type: 'verb', level: 'A2' },
    { word: 'passenger', turkishTranslation: 'yolcu', definitionTr: 'Seyahat eden', exampleSentence: 'All passengers must board now.', exampleSentenceTr: 'Tüm yolcular şimdi binmeli.', type: 'noun', level: 'A2' },
    { word: 'passport', turkishTranslation: 'pasaport', definitionTr: 'Kimlik belgesi', exampleSentence: 'Do not forget your passport.', exampleSentenceTr: 'Pasaportunuzu unutmayın.', type: 'noun', level: 'A1' },
    { word: 'photograph', turkishTranslation: 'fotoğraf', definitionTr: 'Resim', exampleSentence: 'Can I take a photograph?', exampleSentenceTr: 'Fotoğraf çekebilir miyim?', type: 'noun', level: 'A2' },
    { word: 'pilgrimage', turkishTranslation: 'hac', definitionTr: 'Dini ziyaret', exampleSentence: 'They went on a pilgrimage.', exampleSentenceTr: 'Hacca gittiler.', type: 'noun', level: 'B2' },
    { word: 'platform', turkishTranslation: 'peron', definitionTr: 'Tren durağı', exampleSentence: 'The train leaves from platform 3.', exampleSentenceTr: 'Tren 3. perondan kalkıyor.', type: 'noun', level: 'A2' },
    { word: 'postcard', turkishTranslation: 'kartpostal', definitionTr: 'Resimli kart', exampleSentence: 'I sent a postcard home.', exampleSentenceTr: 'Eve kartpostal gönderdim.', type: 'noun', level: 'A2' },
    { word: 'railway', turkishTranslation: 'demiryolu', definitionTr: 'Tren yolu', exampleSentence: 'The railway station is nearby.', exampleSentenceTr: 'Tren istasyonu yakında.', type: 'noun', level: 'B1' },
    { word: 'reception', turkishTranslation: 'resepsiyon', definitionTr: 'Otel girişi', exampleSentence: 'Leave your key at reception.', exampleSentenceTr: 'Anahtarınızı resepsiyona bırakın.', type: 'noun', level: 'A2' },
    { word: 'recommend', turkishTranslation: 'tavsiye etmek', definitionTr: 'Önermek', exampleSentence: 'Can you recommend a restaurant?', exampleSentenceTr: 'Bir restoran tavsiye edebilir misiniz?', type: 'verb', level: 'A2' },
    { word: 'rental', turkishTranslation: 'kiralama', definitionTr: 'Ödünç alma', exampleSentence: 'I need a car rental.', exampleSentenceTr: 'Araba kiralamaya ihtiyacım var.', type: 'noun', level: 'B1' },
    { word: 'reservation', turkishTranslation: 'rezervasyon', definitionTr: 'Yer ayırma', exampleSentence: 'I have a reservation.', exampleSentenceTr: 'Rezervasyonum var.', type: 'noun', level: 'A2' },
    { word: 'resort', turkishTranslation: 'tatil köyü', definitionTr: 'Tatil yeri', exampleSentence: 'We stayed at a beach resort.', exampleSentenceTr: 'Sahil tatil köyünde kaldık.', type: 'noun', level: 'B1' },
    { word: 'return', turkishTranslation: 'dönüş', definitionTr: 'Geri gelme', exampleSentence: 'When is your return flight?', exampleSentenceTr: 'Dönüş uçuşunuz ne zaman?', type: 'noun', level: 'A2' },
    { word: 'route', turkishTranslation: 'rota', definitionTr: 'Yol güzergahı', exampleSentence: 'What route should I take?', exampleSentenceTr: 'Hangi rotayı izlemeliyim?', type: 'noun', level: 'B1' },
    { word: 'scenery', turkishTranslation: 'manzara', definitionTr: 'Doğal görünüm', exampleSentence: 'The scenery here is beautiful.', exampleSentenceTr: 'Buradaki manzara güzel.', type: 'noun', level: 'B1' },
    { word: 'seaside', turkishTranslation: 'deniz kenarı', definitionTr: 'Sahil', exampleSentence: 'We went to the seaside.', exampleSentenceTr: 'Deniz kenarına gittik.', type: 'noun', level: 'A2' },
    { word: 'shuttle', turkishTranslation: 'servis', definitionTr: 'Kısa mesafe aracı', exampleSentence: 'Take the airport shuttle.', exampleSentenceTr: 'Havalimanı servisini kullanın.', type: 'noun', level: 'B1' },
    { word: 'sightseeing', turkishTranslation: 'gezi', definitionTr: 'Yer görme', exampleSentence: 'We went sightseeing today.', exampleSentenceTr: 'Bugün geziye çıktık.', type: 'noun', level: 'A2' },
    { word: 'souvenir', turkishTranslation: 'hediyelik eşya', definitionTr: 'Hatıra', exampleSentence: 'I bought some souvenirs.', exampleSentenceTr: 'Birkaç hediyelik eşya aldım.', type: 'noun', level: 'A2' },
    { word: 'suitcase', turkishTranslation: 'bavul', definitionTr: 'Valiz', exampleSentence: 'My suitcase is too heavy.', exampleSentenceTr: 'Bavulum çok ağır.', type: 'noun', level: 'A2' },
    { word: 'sunbathe', turkishTranslation: 'güneşlenmek', definitionTr: 'Güneş banyosu', exampleSentence: 'I love to sunbathe on the beach.', exampleSentenceTr: 'Sahilde güneşlenmeyi seviyorum.', type: 'verb', level: 'B1' },
    { word: 'sunrise', turkishTranslation: 'gün doğumu', definitionTr: 'Güneşin doğuşu', exampleSentence: 'We watched the sunrise.', exampleSentenceTr: 'Gün doğumunu izledik.', type: 'noun', level: 'A2' },
    { word: 'sunset', turkishTranslation: 'gün batımı', definitionTr: 'Güneşin batışı', exampleSentence: 'The sunset was amazing.', exampleSentenceTr: 'Gün batımı muhteşemdi.', type: 'noun', level: 'A2' },
    { word: 'terminal', turkishTranslation: 'terminal', definitionTr: 'Havalimanı binası', exampleSentence: 'Which terminal is my flight?', exampleSentenceTr: 'Uçuşum hangi terminalde?', type: 'noun', level: 'B1' },
    { word: 'ticket', turkishTranslation: 'bilet', definitionTr: 'Giriş belgesi', exampleSentence: 'I need to buy a train ticket.', exampleSentenceTr: 'Tren bileti almam lazım.', type: 'noun', level: 'A1' },
    { word: 'tip', turkishTranslation: 'bahşiş', definitionTr: 'Para ödülü', exampleSentence: 'Should I leave a tip?', exampleSentenceTr: 'Bahşiş bırakmalı mıyım?', type: 'noun', level: 'A2' },
    { word: 'tour', turkishTranslation: 'tur', definitionTr: 'Gezinti', exampleSentence: 'We took a city tour.', exampleSentenceTr: 'Şehir turuna katıldık.', type: 'noun', level: 'A2' },
    { word: 'tourism', turkishTranslation: 'turizm', definitionTr: 'Gezi sektörü', exampleSentence: 'Tourism is important here.', exampleSentenceTr: 'Turizm burada önemli.', type: 'noun', level: 'B1' },
    { word: 'tourist', turkishTranslation: 'turist', definitionTr: 'Gezgin', exampleSentence: 'There are many tourists here.', exampleSentenceTr: 'Burada çok turist var.', type: 'noun', level: 'A1' },
    { word: 'transfer', turkishTranslation: 'aktarma', definitionTr: 'Geçiş', exampleSentence: 'We have a transfer in Paris.', exampleSentenceTr: 'Paris\'te aktarmamız var.', type: 'noun', level: 'B1' },
    { word: 'travel', turkishTranslation: 'seyahat etmek', definitionTr: 'Gezi yapmak', exampleSentence: 'I love to travel.', exampleSentenceTr: 'Seyahat etmeyi seviyorum.', type: 'verb', level: 'A1' },
    { word: 'trip', turkishTranslation: 'gezi', definitionTr: 'Yolculuk', exampleSentence: 'Have a nice trip!', exampleSentenceTr: 'İyi yolculuklar!', type: 'noun', level: 'A1' },
    { word: 'vacation', turkishTranslation: 'tatil', definitionTr: 'İzin dönemi', exampleSentence: 'I need a vacation.', exampleSentenceTr: 'Tatile ihtiyacım var.', type: 'noun', level: 'A1' },
    { word: 'view', turkishTranslation: 'manzara', definitionTr: 'Görünüm', exampleSentence: 'The room has a sea view.', exampleSentenceTr: 'Odanın deniz manzarası var.', type: 'noun', level: 'A2' },
    { word: 'visa', turkishTranslation: 'vize', definitionTr: 'Giriş izni', exampleSentence: 'Do I need a visa?', exampleSentenceTr: 'Vizeye ihtiyacım var mı?', type: 'noun', level: 'A2' },
    { word: 'visit', turkishTranslation: 'ziyaret etmek', definitionTr: 'Gidip görmek', exampleSentence: 'We visited the castle.', exampleSentenceTr: 'Kaleyi ziyaret ettik.', type: 'verb', level: 'A1' },
    { word: 'voyage', turkishTranslation: 'deniz yolculuğu', definitionTr: 'Uzun seyahat', exampleSentence: 'The voyage took two weeks.', exampleSentenceTr: 'Yolculuk iki hafta sürdü.', type: 'noun', level: 'B2' },
    { word: 'wander', turkishTranslation: 'dolaşmak', definitionTr: 'Gezmek', exampleSentence: 'We wandered through the streets.', exampleSentenceTr: 'Sokaklarda dolaştık.', type: 'verb', level: 'B1' },
];
