// This file was generated by Prisma
import { defineConfig } from "prisma/config";
import path from "path";
import dotenv from "dotenv";

// Load .env manually
dotenv.config({ path: path.resolve(__dirname, ".env") });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL || "file:./dev.db",
  },
});
