// Compact word database generator
// Run: npx ts-node prisma/generate-words.ts

const WORDS: Record<string, Array<[string, string, string, string, string]>> = {
    // [word, turkishTranslation, type, level, category]
    'Genel': [
        ['abandon', 'terk etmek', 'verb', 'B1', 'Genel'],
        ['ability', 'yetenek', 'noun', 'A2', 'Genel'],
        ['absorb', 'emmek, özümsemek', 'verb', 'B2', 'Genel'],
        ['abundant', 'bol, bereketli', 'adjective', 'B2', 'Genel'],
        ['accelerate', 'hızlandırmak', 'verb', 'B2', 'Genel'],
        ['accurate', 'doğru, kesin', 'adjective', 'B1', 'Genel'],
        ['achieve', 'başarmak', 'verb', 'B1', 'Genel'],
        ['acquire', 'edinmek, kazanmak', 'verb', 'B2', 'Genel'],
        ['adapt', 'uyum sağlamak', 'verb', 'B1', 'Genel'],
        ['adequate', 'yeterli', 'adjective', 'B2', 'Genel'],
        ['admire', 'hayran olmak', 'verb', 'B1', 'Genel'],
        ['adolescent', 'ergen', 'noun', 'B2', 'Genel'],
        ['advocate', 'savunmak', 'verb', 'C1', 'Genel'],
        ['afford', 'karşılayabilmek', 'verb', 'B1', 'Genel'],
        ['aggregate', 'toplamak', 'verb', 'C1', 'Genel'],
        ['agile', 'çevik', 'adjective', 'B2', 'Genel'],
        ['allocate', 'tahsis etmek', 'verb', 'C1', 'Genel'],
        ['ambiguous', 'belirsiz, muğlak', 'adjective', 'B2', 'Genel'],
        ['ample', 'bol, geniş', 'adjective', 'B2', 'Genel'],
        ['anticipate', 'öngörmek', 'verb', 'B2', 'Genel'],
        ['apparent', 'açık, belirgin', 'adjective', 'B2', 'Genel'],
        ['appreciate', 'takdir etmek', 'verb', 'B1', 'Genel'],
        ['appropriate', 'uygun', 'adjective', 'B1', 'Genel'],
        ['arbitrary', 'keyfi, rastgele', 'adjective', 'C1', 'Genel'],
        ['aspire', 'arzulamak', 'verb', 'C1', 'Genel'],
        ['assert', 'iddia etmek', 'verb', 'C1', 'Genel'],
        ['assume', 'varsaymak', 'verb', 'B1', 'Genel'],
        ['astonish', 'şaşırtmak', 'verb', 'B2', 'Genel'],
        ['authentic', 'özgün, gerçek', 'adjective', 'B2', 'Genel'],
        ['aware', 'farkında', 'adjective', 'B1', 'Genel'],
        ['baffle', 'şaşırtmak', 'verb', 'C1', 'Genel'],
        ['benevolent', 'hayırsever', 'adjective', 'C1', 'Genel'],
        ['brief', 'kısa', 'adjective', 'B1', 'Genel'],
        ['capable', 'yetenekli', 'adjective', 'B1', 'Genel'],
        ['cautious', 'tedbirli', 'adjective', 'B2', 'Genel'],
        ['cease', 'durdurmak', 'verb', 'C1', 'Genel'],
        ['chronic', 'kronik', 'adjective', 'B2', 'Genel'],
        ['clarify', 'açıklamak', 'verb', 'B2', 'Genel'],
        ['coincidence', 'tesadüf', 'noun', 'B2', 'Genel'],
        ['compel', 'zorlamak', 'verb', 'C1', 'Genel'],
        ['compensate', 'telafi etmek', 'verb', 'B2', 'Genel'],
        ['competent', 'yetkin', 'adjective', 'B2', 'Genel'],
        ['complex', 'karmaşık', 'adjective', 'B1', 'Genel'],
        ['comprehensive', 'kapsamlı', 'adjective', 'B2', 'Genel'],
        ['compromise', 'uzlaşmak', 'verb', 'B2', 'Genel'],
        ['concentrate', 'yoğunlaşmak', 'verb', 'B1', 'Genel'],
        ['concern', 'endişe', 'noun', 'B1', 'Genel'],
        ['conclude', 'sonuçlandırmak', 'verb', 'B2', 'Genel'],
        ['confident', 'özgüvenli', 'adjective', 'B1', 'Genel'],
        ['conflict', 'çatışma', 'noun', 'B1', 'Genel'],
    ],
    'İş': [
        ['collaborate', 'işbirliği yapmak', 'verb', 'B1', 'İş'],
        ['negotiate', 'müzakere etmek', 'verb', 'B1', 'İş'],
        ['implement', 'uygulamak', 'verb', 'B2', 'İş'],
        ['delegate', 'yetki devretmek', 'verb', 'B2', 'İş'],
        ['revenue', 'gelir', 'noun', 'B2', 'İş'],
        ['stakeholder', 'paydaş', 'noun', 'B2', 'İş'],
        ['deadline', 'son tarih', 'noun', 'B1', 'İş'],
        ['feedback', 'geri bildirim', 'noun', 'B1', 'İş'],
        ['strategy', 'strateji', 'noun', 'B1', 'İş'],
        ['efficiency', 'verimlilik', 'noun', 'B2', 'İş'],
        ['agenda', 'gündem', 'noun', 'B2', 'İş'],
        ['benchmark', 'ölçüt', 'noun', 'C1', 'İş'],
        ['budget', 'bütçe', 'noun', 'B1', 'İş'],
        ['client', 'müşteri', 'noun', 'B1', 'İş'],
        ['consultant', 'danışman', 'noun', 'B2', 'İş'],
        ['contract', 'sözleşme', 'noun', 'B1', 'İş'],
        ['corporate', 'kurumsal', 'adjective', 'B2', 'İş'],
        ['entrepreneur', 'girişimci', 'noun', 'B2', 'İş'],
        ['execute', 'yürütmek', 'verb', 'B2', 'İş'],
        ['franchise', 'bayilik', 'noun', 'C1', 'İş'],
        ['incentive', 'teşvik', 'noun', 'B2', 'İş'],
        ['invoice', 'fatura', 'noun', 'B2', 'İş'],
        ['leverage', 'kaldıraç, yararlanmak', 'verb', 'C1', 'İş'],
        ['liability', 'sorumluluk, yükümlülük', 'noun', 'C1', 'İş'],
        ['margin', 'kar marjı', 'noun', 'B2', 'İş'],
        ['merger', 'birleşme', 'noun', 'C1', 'İş'],
        ['monopoly', 'tekel', 'noun', 'B2', 'İş'],
        ['outsource', 'dış kaynak kullanmak', 'verb', 'C1', 'İş'],
        ['partnership', 'ortaklık', 'noun', 'B1', 'İş'],
        ['procurement', 'tedarik', 'noun', 'C1', 'İş'],
        ['profitable', 'karlı', 'adjective', 'B2', 'İş'],
        ['promotion', 'terfi', 'noun', 'B1', 'İş'],
        ['quota', 'kota', 'noun', 'B2', 'İş'],
        ['recruit', 'işe almak', 'verb', 'B2', 'İş'],
        ['restructure', 'yeniden yapılandırmak', 'verb', 'C1', 'İş'],
        ['shareholder', 'hissedar', 'noun', 'B2', 'İş'],
        ['subsidiary', 'bağlı şirket', 'noun', 'C1', 'İş'],
        ['supply', 'tedarik etmek', 'verb', 'B1', 'İş'],
        ['turnover', 'ciro', 'noun', 'B2', 'İş'],
        ['venture', 'girişim', 'noun', 'B2', 'İş'],
    ],
    'Akademik': [
        ['analyze', 'analiz etmek', 'verb', 'B1', 'Akademik'],
        ['hypothesis', 'hipotez', 'noun', 'B2', 'Akademik'],
        ['methodology', 'metodoloji', 'noun', 'C1', 'Akademik'],
        ['thesis', 'tez', 'noun', 'B2', 'Akademik'],
        ['empirical', 'deneysel', 'adjective', 'C1', 'Akademik'],
        ['criterion', 'ölçüt', 'noun', 'B2', 'Akademik'],
        ['paradigm', 'paradigma', 'noun', 'C1', 'Akademik'],
        ['phenomenon', 'fenomen, olgu', 'noun', 'B2', 'Akademik'],
        ['abstract', 'soyut', 'adjective', 'B2', 'Akademik'],
        ['coherent', 'tutarlı', 'adjective', 'C1', 'Akademik'],
        ['derive', 'türetmek', 'verb', 'B2', 'Akademik'],
        ['discourse', 'söylem', 'noun', 'C1', 'Akademik'],
        ['elaborate', 'detaylandırmak', 'verb', 'B2', 'Akademik'],
        ['evaluate', 'değerlendirmek', 'verb', 'B1', 'Akademik'],
        ['explicit', 'açık, belirgin', 'adjective', 'B2', 'Akademik'],
        ['fundamental', 'temel', 'adjective', 'B2', 'Akademik'],
        ['implicit', 'örtük, ima edilen', 'adjective', 'C1', 'Akademik'],
        ['inference', 'çıkarım', 'noun', 'C1', 'Akademik'],
        ['inherent', 'doğasında olan', 'adjective', 'C1', 'Akademik'],
        ['innovative', 'yenilikçi', 'adjective', 'B1', 'Akademik'],
        ['legitimate', 'meşru', 'adjective', 'C1', 'Akademik'],
        ['notion', 'kavram', 'noun', 'B2', 'Akademik'],
        ['objective', 'nesnel', 'adjective', 'B2', 'Akademik'],
        ['perspective', 'bakış açısı', 'noun', 'B2', 'Akademik'],
        ['plausible', 'makul, akla yatkın', 'adjective', 'C1', 'Akademik'],
        ['predominant', 'baskın, hakim', 'adjective', 'C1', 'Akademik'],
        ['preliminary', 'ön, başlangıç', 'adjective', 'C1', 'Akademik'],
        ['prevalent', 'yaygın', 'adjective', 'C1', 'Akademik'],
        ['profound', 'derin, köklü', 'adjective', 'C1', 'Akademik'],
        ['qualitative', 'niteliksel', 'adjective', 'C1', 'Akademik'],
        ['quantitative', 'niceliksel', 'adjective', 'C1', 'Akademik'],
        ['rationale', 'gerekçe', 'noun', 'C1', 'Akademik'],
        ['relevant', 'ilgili', 'adjective', 'B1', 'Akademik'],
        ['rigorous', 'titiz, sıkı', 'adjective', 'C1', 'Akademik'],
        ['scrutinize', 'incelemek', 'verb', 'B2', 'Akademik'],
        ['significant', 'önemli, anlamlı', 'adjective', 'B1', 'Akademik'],
        ['subjective', 'öznel', 'adjective', 'B2', 'Akademik'],
        ['subsequent', 'sonraki', 'adjective', 'C1', 'Akademik'],
        ['theoretical', 'teorik', 'adjective', 'B2', 'Akademik'],
        ['valid', 'geçerli', 'adjective', 'B1', 'Akademik'],
    ],
    'Teknoloji': [
        ['algorithm', 'algoritma', 'noun', 'B2', 'Teknoloji'],
        ['bandwidth', 'bant genişliği', 'noun', 'C1', 'Teknoloji'],
        ['compatible', 'uyumlu', 'adjective', 'B2', 'Teknoloji'],
        ['database', 'veritabanı', 'noun', 'B1', 'Teknoloji'],
        ['debug', 'hata ayıklamak', 'verb', 'B2', 'Teknoloji'],
        ['deploy', 'dağıtmak', 'verb', 'B2', 'Teknoloji'],
        ['encrypt', 'şifrelemek', 'verb', 'B2', 'Teknoloji'],
        ['firewall', 'güvenlik duvarı', 'noun', 'B2', 'Teknoloji'],
        ['interface', 'arayüz', 'noun', 'B1', 'Teknoloji'],
        ['iterate', 'yinelemek', 'verb', 'C1', 'Teknoloji'],
        ['latency', 'gecikme', 'noun', 'C1', 'Teknoloji'],
        ['malware', 'kötü amaçlı yazılım', 'noun', 'B2', 'Teknoloji'],
        ['optimize', 'optimize etmek', 'verb', 'B2', 'Teknoloji'],
        ['prototype', 'prototip', 'noun', 'B2', 'Teknoloji'],
        ['scalable', 'ölçeklenebilir', 'adjective', 'C1', 'Teknoloji'],
        ['simulate', 'simüle etmek', 'verb', 'B2', 'Teknoloji'],
        ['synchronize', 'senkronize etmek', 'verb', 'B2', 'Teknoloji'],
        ['upgrade', 'yükseltmek', 'verb', 'B1', 'Teknoloji'],
        ['virtual', 'sanal', 'adjective', 'B1', 'Teknoloji'],
        ['vulnerability', 'güvenlik açığı', 'noun', 'C1', 'Teknoloji'],
    ],
    'Seyahat': [
        ['accommodate', 'barındırmak', 'verb', 'B2', 'Seyahat'],
        ['itinerary', 'seyahat planı', 'noun', 'B2', 'Seyahat'],
        ['destination', 'varış noktası', 'noun', 'B1', 'Seyahat'],
        ['excursion', 'gezi', 'noun', 'B2', 'Seyahat'],
        ['customs', 'gümrük', 'noun', 'B1', 'Seyahat'],
        ['boarding', 'biniş', 'noun', 'B1', 'Seyahat'],
        ['currency', 'para birimi', 'noun', 'B1', 'Seyahat'],
        ['departure', 'kalkış', 'noun', 'B1', 'Seyahat'],
        ['luggage', 'bagaj', 'noun', 'A2', 'Seyahat'],
        ['passport', 'pasaport', 'noun', 'A2', 'Seyahat'],
        ['reservation', 'rezervasyon', 'noun', 'B1', 'Seyahat'],
        ['souvenir', 'hatıra', 'noun', 'B1', 'Seyahat'],
        ['terminal', 'terminal', 'noun', 'B1', 'Seyahat'],
        ['tourist', 'turist', 'noun', 'A2', 'Seyahat'],
        ['transit', 'transit', 'noun', 'B1', 'Seyahat'],
        ['vaccinate', 'aşılamak', 'verb', 'B2', 'Seyahat'],
        ['voyage', 'yolculuk', 'noun', 'B2', 'Seyahat'],
        ['wander', 'dolaşmak', 'verb', 'B2', 'Seyahat'],
        ['embassy', 'büyükelçilik', 'noun', 'B2', 'Seyahat'],
        ['expedition', 'keşif gezisi', 'noun', 'B2', 'Seyahat'],
    ],
    'Sağlık': [
        ['alleviate', 'hafifletmek', 'verb', 'B2', 'Sağlık'],
        ['diagnosis', 'teşhis', 'noun', 'B2', 'Sağlık'],
        ['symptom', 'semptom', 'noun', 'B1', 'Sağlık'],
        ['therapy', 'terapi', 'noun', 'B2', 'Sağlık'],
        ['prescription', 'reçete', 'noun', 'B2', 'Sağlık'],
        ['contagious', 'bulaşıcı', 'adjective', 'B2', 'Sağlık'],
        ['immune', 'bağışık', 'adjective', 'B2', 'Sağlık'],
        ['nutrition', 'beslenme', 'noun', 'B2', 'Sağlık'],
        ['rehabilitation', 'rehabilitasyon', 'noun', 'C1', 'Sağlık'],
        ['surgical', 'cerrahi', 'adjective', 'B2', 'Sağlık'],
        ['allergy', 'alerji', 'noun', 'B1', 'Sağlık'],
        ['antibiotic', 'antibiyotik', 'noun', 'B1', 'Sağlık'],
        ['chronic', 'kronik', 'adjective', 'B2', 'Sağlık'],
        ['epidemic', 'salgın', 'noun', 'B2', 'Sağlık'],
        ['fatigue', 'yorgunluk', 'noun', 'B2', 'Sağlık'],
        ['genetic', 'genetik', 'adjective', 'B2', 'Sağlık'],
        ['hygiene', 'hijyen', 'noun', 'B1', 'Sağlık'],
        ['inflammation', 'iltihaplanma', 'noun', 'C1', 'Sağlık'],
        ['metabolism', 'metabolizma', 'noun', 'B2', 'Sağlık'],
        ['vaccine', 'aşı', 'noun', 'B1', 'Sağlık'],
    ],
};

// Export for use in seed script
export default WORDS;

// Total count
let total = 0;
for (const cat of Object.values(WORDS)) total += cat.length;
console.log(`📊 Total words in database: ${total}`);
console.log(`📁 Categories: ${Object.keys(WORDS).join(', ')}`);
