'use client';

import {
  AlertTriangle, RefreshCw, Home, SearchX, PlayCircle, GraduationCap,
  Headphones, Star, ArrowLeft, Volume2, CheckCircle, XCircle, ArrowRight,
  Edit, FileEdit, Inbox, Trophy, MicOff, Mic, HelpCircle, Clock,
  ArrowLeftRight, Lightbulb, Check, Lock, Medal, TrendingUp, Calendar,
  Wand2, Sparkles, Send, Mail, BookOpen, CheckCircle2, Brain, Target,
  Smile, Zap, Gem, Plus, PlusCircle, ArrowUp, X, Wrench, Crown,
  LayoutDashboard, Trash2, BookMarked, ChevronDown, Compass, Flag,
  Folder, FolderOpen, Quote, Users, Globe, BarChart3, Activity, Flame,
  Tag, LogIn, LogOut, BarChart, MoreVertical, Bell, BellOff, CreditCard,
  User, UserX, PieChart, ListPlus, Rocket, Save, Search, Settings,
  ShieldCheck, Languages, Megaphone, AlertCircle, Dices, MousePointer2,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  warning: AlertTriangle,
  error: AlertCircle,
  refresh: RefreshCw,
  sync: RefreshCw,
  home: Home,
  search_off: SearchX,
  search: Search,
  play_circle: PlayCircle,
  school: GraduationCap,
  headphones: Headphones,
  star: Star,
  arrow_back: ArrowLeft,
  volume_up: Volume2,
  check_circle: CheckCircle,
  cancel: XCircle,
  close: X,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  edit_off: Edit,
  edit_note: FileEdit,
  edit: Edit,
  inbox: Inbox,
  emoji_events: Trophy,
  trophy: Trophy,
  mic_off: MicOff,
  mic: Mic,
  speech_to_text: Mic,
  quiz: HelpCircle,
  schedule: Clock,
  swap_horiz: ArrowLeftRight,
  lightbulb: Lightbulb,
  check: Check,
  lock: Lock,
  military_tech: Medal,
  trending_up: TrendingUp,
  calendar_today: Calendar,
  auto_fix: Wand2,
  auto_awesome: Sparkles,
  stars: Sparkles,
  send: Send,
  mail: Mail,
  menu_book: BookOpen,
  dictionary: BookMarked,
  verified: CheckCircle2,
  psychology: Brain,
  track_changes: Target,
  target: Target,
  sentiment_satisfied: Smile,
  bolt: Zap,
  diamond: Gem,
  workspace_premium: Crown,
  crown: Crown,
  add: Plus,
  add_circle: PlusCircle,
  playlist_add: ListPlus,
  casino: Dices,
  construction: Wrench,
  dashboard: LayoutDashboard,
  delete: Trash2,
  expand_more: ChevronDown,
  explore: Compass,
  flag: Flag,
  folder: Folder,
  folder_open: FolderOpen,
  format_quote: Quote,
  group: Users,
  language: Globe,
  public: Globe,
  translate: Languages,
  leaderboard: BarChart3,
  local_activity: Activity,
  local_fire_department: Flame,
  local_offer: Tag,
  login: LogIn,
  logout: LogOut,
  monitoring: BarChart,
  more_vert: MoreVertical,
  notifications: Bell,
  notifications_off: BellOff,
  payments: CreditCard,
  person: User,
  person_add_disabled: UserX,
  pie_chart: PieChart,
  rocket_launch: Rocket,
  save: Save,
  settings: Settings,
  shield_person: ShieldCheck,
  touch_app: MousePointer2,
  campaign: Megaphone,
};

interface IconProps {
  name: string;
  size?: number;
  className?: string;
}

export function Icon({ name, size = 20, className }: IconProps) {
  const IconComponent = iconMap[name] ?? HelpCircle;
  return <IconComponent size={size} className={className} />;
}
